### ISSUE TITLE
uuid4 and grouptag not quoted

### ISSUE THREAD

**Issue by I-mpossible** [microsoft/restler-fuzzer#103]
I'm using this spec
https://github.com/jdegre/5GC_APIs/blob/master/TS29518_Namf_Communication.yaml

In grammar.py generated by compiler, there's option quoted=True. But capturing with wireshark shows that it's not quoted.
```primitives.restler_static_string("""
                        }
                    ,
                    "smsfId":"""),
    primitives.restler_fuzzable_uuid4("566048da-ed19-4cd3-8e0a-b7e0e1ec4d72", quoted=True),
```

![image](https://user-images.githubusercontent.com/26900284/101270407-be851b00-37b3-11eb-8363-544767f5c7ab.png)

Same thing happens with grouptag
```
primitives.restler_fuzzable_group("fuzzable_group_tag", ['3GPP_ACCESS','NON_3GPP_ACCESS']  ,quoted=True),
```

![image](https://user-images.githubusercontent.com/26900284/101270444-04da7a00-37b4-11eb-8811-99282a7f6980.png)

**Comment by rifiles** [comment]
Hello,

Thanks a lot for filing this issue and providing the detailed description. We'll look into this right away.
