### ISSUE TITLE
Update Namespace Rule checker to stop replaying the last request

### ISSUE THREAD

**Issue by rifiles** [microsoft/restler-fuzzer#112]
Currently the namespace rule checker replays the entire sequence prior to sending the attack request.  In the case of DELETE requests, resending that request can lead to false negatives because the resource would typically be successfully deleted during the replay.  The checker's attack request would then receive a response akin to a 404, which would not trigger a bug in the checker even if the attack request would have otherwise been successful.

**Comment by PatGod** [comment]
Related to issue/question #104
