### ISSUE TITLE
Compiler crashes when running on https://api.hackerone.com/v1/api-docs/v1/swagger.json

### ISSUE THREAD

**Issue by stishkin** [microsoft/restler-fuzzer#122]
tried to run RESTler on https://api.hackerone.com/v1/api-docs/v1/swagger.json

RESTler compiler crashed with :
 
Unhandled exception. System.AggregateException: One or more errors occurred. (Could not resolve the path '#/components/schemas/automated_remediation_guidance'.)
 ---> System.InvalidOperationException: Could not resolve the path '#/components/schemas/automated_remediation_guidance'.

**Comment by marina-p** [comment]
@stishkin This looks like a bug in the specification.  That path is not present in the specification, which causes the parsing exception.
