### ISSUE TITLE
Queries regarding Compiling

### ISSUE THREAD

**Issue by chanduaki** [microsoft/restler-fuzzer#127]
# Summary

Showing code code zero, even though all tests were run 

```
Log share was not specified.  Logs will not be uploaded.
Starting task Fuzz...
Request coverage (successful / total): 0 / 19
No bugs were found.
Task Fuzz succeeded.
Collecting logs...
```

**Comment by marina-p** [comment]
Hello @chanduaki,

Depending on your API, you may need to further configure the auto-generated files from the compilation step and other settings passed to the engine (dictionary, authentication, etc.).  Please see the documentation here for an explanation of how to improve coverage:  /docs/user-guide/ImprovingCoverage.md.

Please let us know if you run into specific issues with the configuration for your API.
