### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by ruowan** [microsoft/restler-fuzzer#129]
I try to run restler-fuzzer against demo service. But I got this error.

```  
File "/home/ruowan/work/restler-fuzzer/restler_bin/restler/../engine/restler.py", line 53
    grammar_file = f'restler_grammar_{grammar_name}_{os.getpid()}.py'
                                                                    ^
SyntaxError: invalid syntax
```

**Comment by marina-p** [comment]
Hello @ruowan,

Could you please share the full command line you used to invoke RESTler, and also the output of ```python --version```?

**Comment by ruowan** [comment]
Full command
```
../restler_bin/restler/Restler test --grammar_file ./Compile/grammar.py --dictionary_file ./Compile/dict.json --settings ./Compile/engine_settings.json --no_ssl
```

$ python --version
Python 3.8.0

**Comment by jagijagijag1** [comment]
I had the same problem, but the following works for me.

```bash
$ which python
/usr/bin/python

$ ls -la /usr/bin/python
lrwxrwxrwx ... /usr/bin/python -> python2

$ which python3
/usr/local/bin/python3

$ ln -fs /usr/local/bin/python3 /usr/bin/python
```

In my environment, although `python --version` outputs Python 3.8.x due to the alias like `alias python="python3"`, RESTler seems to use `/usr/bin/python` that is a symbolic link to Python 2.x.
So changing the symbolic link solved the problem in my case.

Hope it works for you.

**Comment by PatGod** [comment]
Hopefully, this new option might also be helpful: https://github.com/microsoft/restler-fuzzer/pull/158

Thanks to @jagijagijag1 for your help!

**Comment by marina-p** [comment]
I've also confirmed this error is present when using Python 3.6, but not 3.8.  

RESTler was updated recently to explicitly look for 'python3', as part of #158, in addition to the new option to specify the python path.  Please let us know if this resolves your issue.
