### ISSUE TITLE
Adding token_refresh_command causes fuzzer to skip testing

### ISSUE THREAD

**Issue by victomteng1997** [microsoft/restler-fuzzer#136]
I am trying to add python script to generate login token as described in #75 , and I'm basically using the same token generation script.

The fuzzer works normally when I don't add `--token_refresh_command` and `--token_refresh_interval`.
When I try to execute command 
`./Restler.exe test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings Compile/engine_settings.json --no_ssl --token_refresh_command "python <full-directory>/login.py" --token_refresh_interval 5000`, I can see from server log that the login script was executed, yet no further requests are sent and fuzzer just stop with the following output in few seconds.

> Log share was not specified.  Logs will not be uploaded.
> Starting task Test...
> Request coverage (successful / total): 0 / 35
> No bugs were found.
> Task Test succeeded.
> Collecting logs...

May I know if (1) how to correctly configure token header through token_refresh_command, and (2) any way to just hard code the token in the programme, since I don't need it to be refreshed?

**Comment by marina-p** [comment]
Hello @victomteng1997,

If you haven't already tried this - to debug this, the simplest approach is to print a static value from your python token refresh script (it sounds like maybe this is what you need anyway), so your python script will look like:
```
print("{u'myapp': {}}")
print("ApiTokenTag: 9A")
```

(The format is documented in /docs/user-guide/Authentication.md.  The first line is a required metadata line for all the tokens.)

If this doesn't help identify the issue, can you share the output of the script after the "New Value" line network.testing log:  
```
... Will refresh token: python <...>
New value: <...>
```
It could be that the format does not match what RESTler expects, and it exits right away when the refresh fails.  

Regarding specifying a hard-coded token - using the above approach is preferred because then RESTler will automatically filter the token values from the logs.  You could also inject custom headers using ```restler_custom_payload_header``` in the dictionary.

**Comment by victomteng1997** [comment]
> Hello @victomteng1997,
> 
> If you haven't already tried this - to debug this, the simplest approach is to print a static value from your python token refresh script (it sounds like maybe this is what you need anyway), so your python script will look like:
> 
> ```
> print("{u'myapp': {}}")
> print("ApiTokenTag: 9A")
> ```
> 
> (The format is documented in /docs/user-guide/Authentication.md. The first line is a required metadata line for all the tokens.)
> 
> If this doesn't help identify the issue, can you share the output of the script after the "New Value" line network.testing log:
> 
> ```
> ... Will refresh token: python <...>
> New value: <...>
> ```
> 
> It could be that the format does not match what RESTler expects, and it exits right away when the refresh fails.
> 
> Regarding specifying a hard-coded token - using the above approach is preferred because then RESTler will automatically filter the token values from the logs. You could also inject custom headers using `restler_custom_payload_header` in the dictionary.

Thank you for the help! 

After some simple debugging, I believe that the problem is in unicode encoding of the metadata. Previously I was using the format of `print("{'myapp': {}}\n")`, and after I switch to the format of `print("{u'myapp': {}}\n")`, the fuzzer functions normally. 

As for `restler_custom_payload_header`, I will also try that approach since it seems to be more robust and easy to debug. 

If no problem, this issue can be closed.

**Comment by jiaxian-lin** [comment]
![image](https://user-images.githubusercontent.com/71680354/122727366-881f7100-d2a9-11eb-919c-03129faafeac.png)
i have same problem and  network.testing log look like this:
![image](https://user-images.githubusercontent.com/71680354/122727569-bdc45a00-d2a9-11eb-910b-e9814c7e40d2.png)

**Comment by PatGod** [comment]
On the second line, can you try printing: 'Authorization: **Bearer** ey...'?

**Comment by jiaxian-lin** [comment]
> On the second line, can you try printing: 'Authorization: **Bearer** ey...'?

![image](https://user-images.githubusercontent.com/71680354/122925382-a02fd880-d31b-11eb-943a-3795eafa1833.png)
yes, But the problem is not solved

**Comment by marina-p** [comment]
Hello @jiaxian-lin,

Could you please try to add the full path to python to the token refresh command:

```--token_refresh_command "<full path to python> <full-directory>/login.py" ```

I believe that confusing message is printed when 'python' is not found.  Please let us know if that solves your issue.

**Comment by jiaxian-lin** [comment]
> Hello @jiaxian-lin,
> 
> Could you please try to add the full path to python to the token refresh command:
> 
> `--token_refresh_command "<full path to python> <full-directory>/login.py" `
> 
> I believe that confusing message is printed when 'python' is not found. Please let us know if that solves your issue.

Thanks for your help,but this situation still exists
![image](https://user-images.githubusercontent.com/71680354/123026591-4c5fd680-d391-11eb-8256-25a40cdaee84.png)
![image](https://user-images.githubusercontent.com/71680354/123026731-8630dd00-d391-11eb-8eb7-3d8f2b1a66a9.png)

**Comment by jiaxian-lin** [comment]
> Hello @jiaxian-lin,
> 
> Could you please try to add the full path to python to the token refresh command:
> 
> `--token_refresh_command "<full path to python> <full-directory>/login.py" `
> 
> I believe that confusing message is printed when 'python' is not found. Please let us know if that solves your issue.

it's work! thank you for the help!
