### ISSUE TITLE
Option to not use SSL certificate verification

### ISSUE THREAD

**Issue by miriver** [microsoft/restler-fuzzer#138]
I propose that an option is added to use SSL without certificate verification.

I have my API service set up locally with a self-signed certificate. Unfortunately, Restler fails to make requests due to the certificate validation failing. Restler doesn't seem to have an option to use SSL but not validating the certificate, only to not use SSL at all.

I was able to fix this myself by changing line 50 in `messaging.py` from
`context = ssl.create_default_context()` to
`context = ssl._create_unverified_context()`.

If this is accepted, I can submit a PR to add an option to do this through the settings and/or command line arguments.

**Comment by marina-p** [comment]
Hello Miguel,

This option should be supported.  It is already being discussed in #92.  

Would you mind testing if the update in branch rifiles/92 works for you, and if so send a PR or let me know it's good to merge?  It includes the change you proposed above, plus adding the option.

Thanks!

Marina

**Comment by marina-p** [comment]
PR is merged, closing the issue.
