### ISSUE TITLE
Support OData fuzzing

### ISSUE THREAD

**Issue by WaelAbuSeada** [microsoft/restler-fuzzer#141]
Can you consider support for OData fuzzing?

I can see there are mainly 2 issues, 
1- parsing path like: /companies({company_id})
2- Dealing with query string options like $filter, $select

**Comment by mynjj** [comment]
Just as reference (and perhaps aiding on capturing requirements @marina-p), 

for the parsing path parameters like `/companies({company_id})` I created this [fork](https://github.com/mynjj/restler-fuzzer) that works for my current use case 😄  .. haven't tested it thoroughly

Would be nice to hear thoughts on this
