### ISSUE TITLE
How to set server authentication during fuzzing？

### ISSUE THREAD

**Issue by heavenmyth** [microsoft/restler-fuzzer#152]
How to set server authentication during fuzzing？

**Comment by marina-p** [comment]
Hello @heavenmyth,

Could you please include more specific information about what type of authentication your service supports?  RESTler currently supports a "token refresh command" which allows you to run an arbitrary program or script to get a fresh token - see /docs/user-guide/Authentication.md

**Comment by heavenmyth** [comment]
hi, I use access_token to make API calls. The content I printed in the gettoken.py script is as follows:
print("{u'app1': {}}")
print(f"Authentication: Bearer {Access_token!s}")

The Access_token is obtained through a script, and I want to confirm whether the format of the printed content is correct.

**Comment by mbiuki** [comment]
See this: https://github.com/microsoft/restler-fuzzer/issues/163

**Comment by heavenmyth** [comment]
Hello @mbiuki ,
I think my authentication settings are correct, but after starting the fuzz test, I don’t see the request reaching the server。

The script to get the token is as follows：
![image](https://user-images.githubusercontent.com/26155539/112118710-99e47000-8bf7-11eb-9763-6415d9f7efc2.png)

Below is the log of my fuzz test，No error message is seen in the test result file，Can you tell me how to troubleshoot the problem？

Run complete.
See E:\restler-fuzzer-testing\Server\restler-fuzzer\results for results.
PS E:\restler-fuzzer-testing\Server\restler-fuzzer> python .\run.py --restler_drop_dir e:\restler-fuzzer\restler_bin
> Downloading OpenAPI Specification from https://dev-hrdc-admin.djicorp.com/v2/api-docs
> Saving OpenAPI Specification to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\swagger.json
> Writing config to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\config.json
> Writing engine settings to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\engine_settings.json
> dotnet e:\restler-fuzzer\restler_bin\restler\Restler.dll compile E:\restler-fuzzer-testing\Server\restler-fuzzer\results\config.json
Log share was not specified.  Logs will not be uploaded.
Starting task Compile...
Task Compile succeeded.

> dotnet e:\restler-fuzzer\restler_bin\restler\Restler.dll test --grammar_file E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Compile\grammar.py --dictionary_file E:\restler-fu
ler-fuzzer\results\Compile\dict.json --settings E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Compile\engine_settings.json  --no_ssl --host dev-hrdc-admin.djicorp.com
Log share was not specified.  Logs will not be uploaded.
Starting task Test...

ERROR: Restler engine failed. See logs in E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Test directory for more information.

**Comment by mbiuki** [comment]
I think you posted the same as above in https://github.com/microsoft/restler-fuzzer/issues/166.
To avoid redundancy, could you please post your problems in one thread only. See my response in https://github.com/microsoft/restler-fuzzer/issues/166,

**Comment by marina-p** [comment]
Closing this issue since it is a duplicate of #166
