### ISSUE TITLE
Projct maturity and roadmap

### ISSUE THREAD

**Issue by LYDE1234** [microsoft/restler-fuzzer#155]
Great project! my concern is: what's the current maturity level and roadmap? I'm trying this out for our organization and would like to communicate clearly how reliable and future-proof RESTler will be if we decide to build our fuzz testing strategy around it.

**Comment by marina-p** [comment]
Hello @LYDE1234,

Restler is MIT licensed open source, in continuous use at Microsoft and being adopted around the world.  For info on support expectations for the project, see the section in /docs/contributor-guide/Contributing.md.  

Thanks,

Marina
