### ISSUE TITLE
Restler engine failed

### ISSUE THREAD

**Issue by heavenmyth** [microsoft/restler-fuzzer#166]
I think my authentication settings are correct, but after starting the fuzz test, I don’t see the request reaching the server。

The script to get the token is as follows：
![image](https://user-images.githubusercontent.com/26155539/112130156-22b4d900-8c03-11eb-9301-375e9e0dcf26.png)

Below is the log of my fuzz test，No error message is seen in the test result file，Can you tell me how to troubleshoot the problem？

Run complete.
See E:\restler-fuzzer-testing\Server\restler-fuzzer\results for results.
PS E:\restler-fuzzer-testing\Server\restler-fuzzer> python .\run.py --restler_drop_dir e:\restler-fuzzer\restler_bin

Downloading OpenAPI Specification from https://xxxxxxxxxxx/v2/api-docs
Saving OpenAPI Specification to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\swagger.json
Writing config to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\config.json
Writing engine settings to E:\restler-fuzzer-testing\Server\restler-fuzzer\results\engine_settings.json
dotnet e:\restler-fuzzer\restler_bin\restler\Restler.dll compile E:\restler-fuzzer-testing\Server\restler-fuzzer\results\config.json
Log share was not specified. Logs will not be uploaded.
Starting task Compile...
Task Compile succeeded.

dotnet e:\restler-fuzzer\restler_bin\restler\Restler.dll test --grammar_file E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Compile\grammar.py --dictionary_file E:\restler-fu
ler-fuzzer\results\Compile\dict.json --settings E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Compile\engine_settings.json --no_ssl --host dev-hrdc-admin.djicorp.com
Log share was not specified. Logs will not be uploaded.
Starting task Test...

ERROR: Restler engine failed. See logs in E:\restler-fuzzer-testing\Server\restler-fuzzer\results\Test directory for more information.

**Comment by mbiuki** [comment]
- You'd have to monitor traffic to be able to see what is going out and what error you are receiving from the server. I had an issue in the past that I should have passed the URLs without "https://" prefix.
- Also see network logs in the Test directory.

**Comment by heavenmyth** [comment]
hello,@mbiuki 

2021-03-24 17:50:17.582: Will refresh token: python E:\restler-fuzzer-testing\Server\restler-fuzzer\gettoken.py
2021-03-24 17:50:18.654: New value: {u'app1': {}}
_OMITTED_AUTH_TOKEN_

Generation-1: Rendering Sequence-1

	Request: 1 (Remaining candidate combinations: 4)
	Request hash: 03188f6d1bb4fddcd4cfa3040c1afaf81e1c6406

		- restler_static_string: 'POST '
		- restler_static_string: '/'
		- restler_static_string: 'api'
		- restler_static_string: '/'
		- restler_static_string: 'dataSync'
		- restler_static_string: '/'
		- restler_static_string: 'synchronizedPSShiftInfo'
		- restler_static_string: ' HTTP/1.1\r\n'
		- restler_static_string: 'Accept: application/json\r\n'
		- restler_static_string: 'Host: dev-hrdc-admin.djicorp.com\r\n'
		- restler_static_string: 'Content-Type: application/json\r\n'
		+ restler_refreshable_authentication_token: ['token_refresh_cmd', 'token_refresh_interval']
		- restler_static_string: '\r\n'
		- restler_static_string: '{'
		- restler_static_string: '\n    "async":'
		- restler_fuzzable_bool: 'true'
		- restler_static_string: ',\n    "begin_dt":'
		+ restler_fuzzable_string: ['"fuzzstring"', '""']
		- restler_static_string: ',\n    "end_dt":'
		+ restler_fuzzable_string: ['"fuzzstring"', '""']
		- restler_static_string: '}'
		- restler_static_string: '\r\n'

2021-03-24 17:50:20.516: Sending: 'POST /api/dataSync/synchronizedPSShiftInfo HTTP/1.1\r\nAccept: application/json\r\nHost: dev-hrdc-admin.djicorp.com\r\nContent-Type: application/json\r\n_OMITTED_AUTH_TOKEN_\r\nContent-Length: 77\r\nUser-Agent: restler/7.2.0\r\n\r\n{\n    "async":true,\n    "begin_dt":"fuzzstring",\n    "end_dt":"fuzzstring"}\r\n'

2021-03-24 17:50:20.570: Received: 'HTTP/1.0 302 Moved Temporarily\r\nLocation: https://dev-hrdc-admin.djicorp.com/api/dataSync/synchronizedPSShiftInfo\r\nServer: BigIP\r\nConnection: Keep-Alive\r\nContent-Length: 0\r\n\r\n'

**Comment by heavenmyth** [comment]
hello,@mbiuki
Does restler support getting my login status for server request?
I got a login state for the service in two steps, and the login state has permission to request the server。
step 1：ret2 = session.post('xxxxxxxxx/users/auth/ldap/callback')
step 2 ：r3=session.post('xxxxxxxxxxxx/oauth/authorize/')

At this point, I can have the permission to request the server, how can I give it to restler。

**Comment by stishkin** [comment]
@heavenmyth  -  can you try to specify the URL that you trying to fuzz as the one returned in 302 response ? 
I could not find any code where RESTler processes 302 correctly and uses redirect URL

https://xxxxxxxxx/api/dataSync/synchronizedPSShiftInfo\r\nServer:

**Comment by mbiuki** [comment]
> hello,@mbiuki
> Does restler support getting my login status for server request?
> I got a login state for the service in two steps, and the login state has permission to request the server。
> step 1：ret2 = session.post('xxxxxxxxx/users/auth/ldap/callback')
> step 2 ：r3=session.post('xxxxxxxxxxxx/oauth/authorize/')
> 
> At this point, I can have the permission to request the server, how can I give it to restler。

I do not know about the above and you should see if the authors have an answer. Usually, cloud services have a JWT token generated with the following sample code (similar to yours):
```
curl -XPOST -H "Content-Type:application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=<client-id>&client_secret=<client-secret>&scope=token" \
                   https://id.xyz.com/api/v4/oauth2/token
```

**Comment by marina-p** [comment]
Closing not-repro.  Please re-open this issue if you are still hitting this and can provide the EngineStdErr.txt and EngineStdOut.txt.
