### ISSUE TITLE
How to set about Basic Authentication in Restler？

### ISSUE THREAD

**Issue by p870613** [microsoft/restler-fuzzer#168]
Hi ,
I want to test the server in Basic Authentication. 
But, I don't know how to do.
I had seen #75. 
I think I need to write python script and it can generate this.
`Authorization: Basic user:passwd`

However, it don't work.

This is my yaml.
![image](https://user-images.githubusercontent.com/23655229/112361230-21bc9e00-8d0e-11eb-963c-d6b447817051.png)

And, this is result.
![image](https://user-images.githubusercontent.com/23655229/112361376-4284f380-8d0e-11eb-8977-dbef91385fef.png)

Thank you !

**Comment by stishkin** [comment]
Do you have  "UseRefreshableToken": true  set in you job configuration ?

**Comment by marina-p** [comment]
@p870613 The "token refresh command" must be a command that, when launched separately on the command line, prints the token.  You need to add your python path to the command (e.g. "/usr/bin/python /path/to/token.py" 

@stishkin "UseRefreshableToken" is no longer required.  If the refresh token command is not passed to the engine, a token will simply not be used

**Comment by mbiuki** [comment]
> @p870613 The "token refresh command" must be a command that, when launched separately on the command line, prints the token. You need to add your python path to the command (e.g. "/usr/bin/python /path/to/token.py"
> 

@p870613 and your `token.py`, should print something like this:

```
{u'db74fa8e-911f-40d5-94aa-774bc21112fc': {}}
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGci............HmC9A4Y
```

Note, at the moment, the second line is only important, i.e., the first line can be any (fake) UUID. But the format should essentially be as above.

**Comment by p870613** [comment]
Ok,
Thanks for your reply,
I will try it again.

**Comment by p870613** [comment]
@mbiuki @marina-p 
Thanks for your reply.
I have already soluted my problem.
![image](https://user-images.githubusercontent.com/23655229/113599579-68e15200-9671-11eb-821a-fc5e86a26678.png)

**Comment by wyunc** [comment]
> @mbiuki @marina-p Thanks for your reply. I have already soluted my problem. ![image](https://user-images.githubusercontent.com/23655229/113599579-68e15200-9671-11eb-821a-fc5e86a26678.png)

Hello, how do you set up your python script?

I need to add a basic token, so in my ’token.py‘ I write the following:

'print("{u'app1': {}}")'    
'print("Authorization: Basic Username:defaultpwd")'

I see an authentication error in the log

**Comment by wyunc** [comment]
> @mbiuki @marina-p Thanks for your reply. I have already soluted my problem. ![image](https://user-images.githubusercontent.com/23655229/113599579-68e15200-9671-11eb-821a-fc5e86a26678.png)

Hello, how do you set up your python script?

I need to add a basic token, so in my ’token.py‘ I write the following:

'print("{u'app1': {}}")'    
'print("Authorization: Basic Username:defaultpwd")'

I see an authentication error in the log

**Comment by wyunc** [comment]
> @mbiuki @marina-p Thanks for your reply. I have already soluted my problem. ![image](https://user-images.githubusercontent.com/23655229/113599579-68e15200-9671-11eb-821a-fc5e86a26678.png)

Hello, how do you set up your python script?

I need to add a basic token, so in my ’token.py‘ I write the following:

'print("{u'app1': {}}")'    
'print("Authorization: Basic Username:defaultpwd")'

I see an authentication error in the log
