### ISSUE TITLE
restler_fuzzable_uuid4 behaving unexpectedly

### ISSUE THREAD

**Issue by PatGod** [microsoft/restler-fuzzer#187]
As discussed, filing a bug for this issue.

Description: here is a grammar.py fragment

```
# Endpoint: /organizationHierarchy/organizations/{orgId}, method: Post
request = requests.Request([
    primitives.restler_static_string("POST "),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("organizationHierarchy"),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("organizations"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_uuid4("566048da-ed19-4cd3-8e0a-b7e0e1ec4d72", quoted=False),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: \r\n"),
    primitives.restler_static_string("Content-Type: application/json\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),
    primitives.restler_static_string("{"),
    primitives.restler_static_string("""
    "organizationName":"""),
    primitives.restler_fuzzable_string("fuzzstring", quoted=True),
    primitives.restler_static_string("}"),
    primitives.restler_static_string("\r\n"),

],
requestId="/organizationHierarchy/organizations/{orgId}"
)
```

Here is the matching entry in the dict.json:
```
 "restler_fuzzable_uuid4": [
    "903bcc44-30cf-4ea7-968a-d9d0da7c072f"
  ],
```
And here is how it is rendered in the network.testing logs:

`2021-04-14 18:00:55.925: Sending: 'POST /organizationHierarchy/organizations/2957be0e92fa461a8b091745bc44699f HTTP/1.1\r\nAccept: application/json\r\nHost: <XXX>\r\nContent-Type: application/json\r\nContent-Length: 40\r\nUser-Agent: restler/7.3.0\r\n\r\n{\n    "organizationName":"fuzzstring"}\r\n'`

Why is **2957be0e92fa461a8b091745bc44699f** not rendered as a GUID with 4 'dashes'?

Is this expected or is it a bug?

(Full repro available upon request.)

**Comment by mbiuki** [comment]
A side note question in this ticket, could you please elaborate what is the difference between `restler_custom_payload_uuid4_suffix`, `restler_custom_payload`, and `restler_fuzzable_uuid4`?

- How the fuzzer is going to treat the above for UUIDs. That is, if I have fixed uuid endpoint parameters, would I just not need to pass them in `restler_custom_payload`? Then, why do we need `restler_fuzzable_uuid4`?

**Comment by PatGod** [comment]
@mbiuki 'restler_custom_payload' is for specifying constants ("magic values"), 'restler_fuzzable_XXX' is for specifying a list of constants to be used for controlled fuzzing, 'restler_custom_payload_uuid4_suffix' appends a random suffix to a constant specified by this option. Please see https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/FuzzingDictionary.md where all these options are defined.

**Comment by samuelspagl** [comment]
Is there any news to this topic? I'm kinda new to using Restler and still learning a lot of things... 
Is there any way to let Restler fuzz UUID's in a correct way, or should I just replace them by static strings / constants? 

Best :)

**Comment by marina-p** [comment]
Hello @samuelspagl,

Yes, for quickly working around this, you can replace by static strings or a custom payload.

It looks like this is a quick fix, so this should be merged soon.

Thanks,

Marina

**Comment by marina-p** [comment]
I merged a fix - please let us know if you see any further issues with uuid types.  (Just FYI, other formats will be supported better with #369.)

**Comment by samuelspagl** [comment]
Hey @marina-p,
Thanks a lot for the short time fix. In my first test, the generation and fuzzing of the UUID worked as expected. The API accepts them without any problem. 

I'm looking forward to the new commit :)
