### ISSUE TITLE
how to generate multiple elements in array ?

### ISSUE THREAD

**Issue by p870613** [microsoft/restler-fuzzer#197]
Hi, 
I want to generate the array like this
```
{
    "min_max":
        [[0,1]]
} 
```
However, I met some trouble that Restler can't generate it.
Here is the result running `./Restler test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings test.json  --no_ssl`
From this picture, it only generate `min_max:[[ 0 ]]`.
![image](https://user-images.githubusercontent.com/23655229/116774346-995cb600-aa8e-11eb-91bb-99ff01c420d3.png)

Here is my swagger
```
swagger: "2.0"
info:
  title: IoTtalk-v1 csm API Specification
  version: 1.0.0
  description: >-
    This is a IoTtalk server.  You can head to iottalk at
host: "140.113.199.183:9999"


tags:
- name: "List All"
  description: "list all"

- name: "Remote Control"
  description: "Remote Control device"

- name: "msg"
  description: "Related to message"

- name: "SwitchSet"
  description: "CSM API"
  
- name: "CORS"
  description: "Accepted CORS service"

- name: "Pull/Push"
  description: "Get/Send data to IoTtalk"
  
- name: "Register/Deregister"
  description: "De/Register a device profile"

schemes:
- "http"

consumes:
- application/json
produces:
- application/json

paths:
  /dfm/{na_id}/{dfo_id}/{stage}/min_max:
    put:
      tags:
      - "Device Feature Management"
      summary: "dfm_push_min_max"
      #description: ""
      operationId: "dfm_push_min_max"
      parameters:
      - name: na_id
        in: "path"
        description: "Network Application id"
        required: true
        type: integer
      - name: dfo_id
        in: "path"
        description: "device feature object id"
        required: true
        type: integer
      - name: stage
        in: "path"
        required: true
        type: string
      - name: min_max
        in: "body"
        description: "min_max value"
        required: true
        schema:
           $ref : "#/definitions/Min_max" 
      responses:
        "200":
          description: ""
        "400":
          description: "min_max is not given"
definitions:
  Min_max:
    properties:
      min_max:
        type: array
        items:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
    xml:
      name: "Min_max"
``` 

Here is `grammar.py`
```
""" THIS IS AN AUTOMATICALLY GENERATED FILE!"""
from __future__ import print_function
import json
from engine import primitives
from engine.core import requests
from engine.errors import ResponseParsingException
from engine import dependencies
req_collection = requests.RequestCollection([])
# Endpoint: /dfm/{na_id}/{dfo_id}/{stage}/min_max, method: Put
request = requests.Request([
    primitives.restler_static_string("PUT "),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("dfm"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_int("1"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_int("1"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_string("fuzzstring", quoted=False),
    primitives.restler_static_string("/"),
    primitives.restler_static_string("min_max"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    primitives.restler_static_string("Accept: application/json\r\n"),
    primitives.restler_static_string("Host: 140.113.199.183:9999\r\n"),
    primitives.restler_static_string("Content-Type: application/json\r\n"),
    primitives.restler_refreshable_authentication_token("authentication_token_tag"),
    primitives.restler_static_string("\r\n"),
    primitives.restler_static_string("{"),
    primitives.restler_static_string("""
    "min_max":
    [
        [
            """),
    primitives.restler_fuzzable_int("1"),
    primitives.restler_static_string("""
        ]
    ]}"""),
    primitives.restler_static_string("\r\n"),

],
requestId="/dfm/{na_id}/{dfo_id}/{stage}/min_max"
)
req_collection.add_request(request)
```

**Comment by marina-p** [comment]
Hello @p870613,

By default, RESTler will generate 1-element arrays in the grammar.  Then, the payload body checker will fuzz bodies, including varying the number of elements in arrays.  

From the above, it sounds like what you need is specifically a two-element array to get a successful request, is that correct?  The easiest way for you to send 2-element arrays for this specific property is to use ```restler_custom_payload```, by adding the following to the dictionary:.

```
  "restler_custom_payload": {
    "min_max": ["[[1, 2]]", "[[3, 4]]"]
  }
```

Another way is to use an example payload.  

(a)Currently you can provide an example via the method described in Examples.md, but this will not make the elements fuzzable.  

(b)
There is a change currently in PR (mp/examples branch) that will allow providing the examples via the spec, as follows:

min_max:
        type: array
        items:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
        example: 
          [[1, 2]]

With this method, you will get individual fuzzable array elements that will be fuzzed according to the array element type. 

Does this solve what you wanted to do?  If not, could you please provide more details?

Also, I will open a separate issue to support the 'minItems' and 'maxItems' specification, this is not supported right now.

**Comment by p870613** [comment]
Thanks for your reply.
I want to use the first way, that is, add `restler_custom_payload` to `dict.json`.
However, I still meet the trouble like above, only one element.
Do I change my `grammar.py` or something ?

Here is my dict.json
```
{
  "restler_fuzzable_string": [
    "fuzzstring"
  ],
  "restler_fuzzable_string_unquoted": [],
  "restler_fuzzable_datetime": [
    "6/25/2019 12:00:00 AM"
  ],
  "restler_fuzzable_datetime_unquoted": [],
  "restler_fuzzable_uuid4": [
    "903bcc44-30cf-4ea7-968a-d9d0da7c072f"
  ],
  "restler_fuzzable_uuid4_unquoted": [],
  "restler_fuzzable_int": [
    "0",
    "1"
  ],
  "restler_fuzzable_number": [
    "0.1",
    "1.2"
  ],
  "restler_fuzzable_bool": [
    "true"
  ],
  "restler_fuzzable_object": [
    "{}"
  ],
  "restler_custom_payload": {
    "min_max": ["[[1, 2]]", "[[3, 4]]"]
  },
  "restler_custom_payload_unquoted": {},
  "restler_custom_payload_uuid4_suffix": {}
}
```

Thank you !

**Comment by p870613** [comment]
Thanks for your reply.
I use the first way, that is, adding  `restler_custom_payload` to `dict.json`.
Like this.
![image](https://user-images.githubusercontent.com/23655229/117113778-8a8f3f80-adbd-11eb-8cb1-8dbeab10b548.png)
However, I edit the `grammar.py` manually like this.
![image](https://user-images.githubusercontent.com/23655229/117114234-27ea7380-adbe-11eb-85f3-0695a1191bb9.png)
It's possible to generate the `primitives.restler_custom_payload("min_max",quoted=False),` automatically by `compile` ??

Thank you !

**Comment by marina-p** [comment]
Yes.  When you compile, you should specify the above dictionary (via the config.json - restler.exe compile <path to config.json>), which includes the custom payload you added above.  The compiler will read all the custom payloads in the dictionary and generate the corresponding grammar primitives.

**Comment by p870613** [comment]
OK,  I have solved my problem.
Thanks!!!

**Comment by rreexxllii0310** [comment]
> Yes. When you compile, you should specify the above dictionary (via the config.json - restler.exe compile ), which includes the custom payload you added above. The compiler will read all the custom payloads in the dictionary and generate the corresponding grammar primitives.

Hi, I've tried the config.json to automatically generate custom payloads in dict.json and grammar.py.
But I got an error while compiling by `./Restler compile config.json`.

My two specifications are under `/restler_bin/restler/spec` dir

My config.json is under `/restler_bin/restler`:
```
1 {
2    "SwaggerSpecConfig": [
3        {
4            "SpecFilePath": "/spec/iottalkv1_ccm_api_swagger2.0_20210328.yaml",
5            "DictionaryFilePath": "ccm_dict.json"
6        },
7        {
8            "SpecFilePath": "/spec/iottalkv1_csm_api_swagger2.0_20210329.yaml",
9            "DictionaryFilePath": "csm_dict.json",
10            "Dictionary": {
11                "restler_custom_payload": {
12                    "min_max": ["[[1, 1]]", "[[1, 2]]", "[[3, 4]]", "[[1, 10]]"]
13                }
14            }
15        }
16     ]
17 }
```

The error is as following:
```
ERROR: Invalid format for compiler config file config.json. Please refer to the documentation for the compiler config file format.

ERROR: Deserialization exception: "An exception occurred during deserialization: Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path '', line 10, position 27."
```

How can I solve it??
Thank you !
