### ISSUE TITLE
Test command not sending any requests

### ISSUE THREAD

**Issue by Gurubg1** [microsoft/restler-fuzzer#200]
Hi,
I have used latest image from Docker hub to setup Restler. Howerver, if I run test command, it does not send any requests. All request related files (runSummary.json, errorBuckets.json etc..) are empty. Following entries can be found in the logs:
2021-05-05T10:40:47.0744743Z Request coverage (successful / total): 0 / 1
2021-05-05T10:40:47.0745209Z No bugs were found.
2021-05-05T10:40:47.0745516Z Task Test succeeded. 
Am I doing anything wrong here?

**Comment by stishkin** [comment]
@Gurubg1 
- what command do you use ? 
- what is your configuration ?
- did the same configuration/command worked on your local RESTler ?

**Comment by Mafti** [comment]
Does your swagger contain the "host" attribute?

**Comment by Gurubg1** [comment]
Following is my command:
dotnet Restler.dll test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json  --host "<base url of the api>" --token_refresh_command "/usr/bin/python3 /RESTlerTokenGetter.py <username> <password>" --token_refresh_interval 720
I did not try running REStler locally. I used the image available in the docker hub to run in a CI/CD pipeline.
@Mafti  My swagger file does not have host attribute. I give it as an argument to test command. Is it required to have it in swagger json?

**Comment by stishkin** [comment]
what command did you use to run RESTler in your CI/CD pipeline ? 

Does your CI/CD pipeline has access to the RESTlerTokenGetter.py ? Since RESTler engine needs to call the script to get the token.

Are there any RESTler network logs inside of experiment folder ?

**Comment by Gurubg1** [comment]
I am using Azure Devops pipeline. There is a task to build and publish docker images. Following is my DockerFile
FROM mcr.microsoft.com/restlerfuzzer/restler:v7.3.0
COPY  ./RESTlerTokenGetter.py .
COPY ./RolesSwaggerDoc.json . 
WORKDIR RESTler/restler
RUN chmod +x Restler.dll
RUN dotnet Restler.dll compile --api_spec ../../RolesSwaggerDoc.json
dotnet Restler.dll test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --host <base_url_of_the_api> --token_refresh_command "/usr/bin/python3 /RESTlerTokenGetter.py <user_name> <pass_word>" --token_refresh_interval 720
There is no problem in accessing RESTlerTokenGetter.py. I have tried adding the token refresh command as a separate statement in my DockerFile and it was able to get a token.
experiment folder is empty.

**Comment by marina-p** [comment]
Hello @Gurubg1,

Question 1:  are you able to run the 'restler_quick_start.py' per documentation in the container? 

Question 2: 
Are there any RESTler log files produced?  
e.g. restler-*.log, EngineStdErr.txt, or EngineStdOut.txt

If yes, could you please attach these files?

**Comment by Gurubg1** [comment]
EngineStdErr.txt seems to be empty. EngineStdOut.txt has following contents:
Initializing: Garbage collection every 30 seconds.
Terminating garbage collection. Waiting for max 300 seconds.
Done.

**Comment by Gurubg1** [comment]
@stishkin I tried to setup Restler locally. If I run the same command locally, network.testing.400044.1.txt contains a line:
2021-05-06 18:16:09.941: 'Exception Creating Socket: [Errno 11001] getaddrinfo failed'
Could this be the problem?

**Comment by mbiuki** [comment]
I have had this issue before. It is not clear by reading the documentation whether we have to add the `HTTPS` prefix or not. I tried a few options including dropping the prefix until it worked. Watching the communication with Wireshark helped too. My suggestion for authors is to update the documentation to describe the format of the host string. For example, other API fuzzers, such as [Schemathesis](https://schemathesis.readthedocs.io/en/stable/introduction.html), would require the inclusion of the `HTTPS` prefix.

**Comment by marina-p** [comment]
Thank you @mbiuki for the suggestion to update the docs.  I will create a new issue for this.
