### ISSUE TITLE
Can the NameSpaceRuleChecker report false alarms?

### ISSUE THREAD

**Issue by Srijan619** [microsoft/restler-fuzzer#213]
As cited in the paper Checking Security Properties of Cloud Service Rest APIs
```
A user namespace violation occurs when a resource created
within the namespace of one user is accessible from within the namespace of another user. If such a violation ever occurs, an attacker might be able to execute REST API requests using an unauthorized authentication token, and perform unauthorized operations on resources belonging to another (victim) user.
```
Isn't this wrong in the sense that a GET request should be okay even if it is in another user's resource? For example in a blog app, a logged in user should be able to read other's blog?

**Comment by PatGod** [comment]
The NameSpaceRuleChecker reports any successful attempt for a user with tokenA to access resources of a user with tokenB.

In some cases, such accesses are indeed legitimate.

To filter out these cases, you can either ignore such alarms when processing the RESTler results or modify the code of this checker by using the _false_alarm function -- see https://github.com/microsoft/restler-fuzzer/blob/main/restler/checkers/README.md
