### ISSUE TITLE
Unhandled exception when processing mattermost API spec

### ISSUE THREAD

**Issue by dagit** [microsoft/restler-fuzzer#215]
It looks restler throws an unhandled exception when processing the API spec at http://api.mattermost.com

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Restler.Compiler.SwaggerVisitors.generateGrammarElementForSchema(JsonSchema schema, FSharpOption`1 exampleValue, Boolean generateFuzzablePayloadsForExamples, FSharpList`1 parents, FSharpFunc`2 cont) in /home/dagit/local-data/restler-fuzzer/src/compiler/Restler.Compiler/SwaggerVisitors.fs:line 414
```

That was the result of issuing the following command:
```
./restler_bin/restler/Restler compile --api_spec mattermost-swagger.json
```

I was able to successfully compile the gitlab spec that can be found in the examples in the openapi repo. So I think my restler build is working correctly. Could it be that mattermost is using an unsupported revision of openapi/swagger?

Thanks!

**Comment by dagit** [comment]
Running `openapi-spec-validator` over the file I get this error:

```
Required list has not defined properties: ['post_duration', 'display_name']
```

Perhaps that's causing the exception?

**Comment by marina-p** [comment]
Hello @dagit,

Thanks for reporting this and it's great you are able to link the full API spec.  This looks like a bug in RESTler itself - we will investigate further and try to get back to you soon with a workaround.

Thanks,

Marina

**Comment by dagit** [comment]
Great! I don't know if you looked at the linked bug but I also reported this to the mattermost developers as it seems that the openapi spec validator found at least one thing it didn't like about their specification.

**Comment by marina-p** [comment]
The problem with the spec is that there are arrays declared without an array item type.  If you remove these two instances, compilation succeeds:

                  "team_ids": {
                    "type": "array",
                    "description": "Filters results to channels belonging to the given team ids\n"
                  },

This should have an 'items' property of type 'string'.  I don't know why this is not being flagged during parsing by NSwag/NJsonSchema (which RESTler uses), or by the open api spec validator, since this is a required property.  

(I'm keeping this issue opened to handle this more gracefully in RESTler)
