### ISSUE TITLE
Remove/skip the subdir "experiment<_pid_>" under RestlerResults directory

### ISSUE THREAD

**Issue by PatGod** [microsoft/restler-fuzzer#240]
Suggestion: remove/skip the "experiment<_pid_>" subdir under RestlerResults.

Thus, the RestlerResults will now be of the form:

`RestlerResults/logs/...`
`RestlerResults/bug_buckets/...`
Etc.

instead of 

`RestlerResults/experiment<_pid_>/logs/...`
`RestlerResults/experiment<_pid_>/bug_buckets/...`
Etc.

Motivation: the random <_pid_> needlessly complicates automatically post-processing the RestlerResults by other tools (e.g., for differential regression testing). 

(Since restler.exe always recreates the Test/FuzzLean/Fuzz sub-directory, there will never be a conflict on "experiment<_pid_>" anymore.)

Warning: implementing this might be a breaking change for any existing post-processing tool!

**Comment by stishkin** [comment]
This will also break RAFT, since we do automatic post processing of RESTler results.

**Comment by marina-p** [comment]
We could first get rid of the random PID, and just have a constant "0".  Stas, would that avoid breaking RAFT?

**Comment by stishkin** [comment]
@marina-p  - it's ok to remove pid altogether. Just let us know when you do it  - so we could adjust our implementation.

**Comment by PatGod** [comment]
Thank you for all your comments.

Yes, a new option `use_fixed_dirname` to control this new behavior makes sense, and setting it off (False) by default would preserve the current behavior and backward-compatibility.

I can submit a PR for this soon.

**Comment by mbiuki** [comment]
This looks like a very good suggestion. It saves one layer of subdir complexity. However, we would have to make changes to our fuzzer post-processing scripts at our front since we are dependent on RESTler logs, too.

**Comment by mbiuki** [comment]
> Thank you for all your comments.
> 
> Yes, a new option `use_fixed_dirname` to control this new behavior makes sense, and setting it off (False) by default would preserve the current behavior and backward-compatibility.
> 
> I can submit a PR for this soon.

Please let us know when this option is implemented and how we can activate it?
Thanks!

**Comment by PatGod** [comment]
Hi @mbiuki Mehdi, this will be implemented shortly with a new option 'save_results_in_fixed_dirname' which you can set to 'true' in the settings.json file - see PR #243 which is currently under review and should be merged very soon.
