### ISSUE TITLE
Cannot import custom mutations: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by michaelgregson** [microsoft/restler-fuzzer#262]
Starting restler with cmd: `Restler.exe test --grammar_file Compile\grammar.py --dictionary_file Compile\dict.json`

Result: `ERROR: Restler engine failed. See logs in \Test directory for more information.`

EngineStdErr is empty; this is the information in EngineStdOut:

`Cannot import custom mutations: 'charmap' codec can't decode byte 0x81 in position 1967: character maps to <undefined>`

I can reliably make happen by including strings from [this repo](https://github.com/minimaxir/big-list-of-naughty-strings) in the restler_fuzzable_string collection in the dictionary.

Thank you in advance

**Comment by marina-p** [comment]
Hello @michaelgregson,

I've merged a fix that resolves the error.  However, it would be great if you could sanity check that the interesting strings are being sent to the server in the way that you expect (please let us know if you see issues).

Aside: if you are going to test a large number of those strings, make sure you increase max_combinations in the engine settings to make sure all those strings get tested.  Also, RESTler is not optimized for testing huge lists of fuzzable strings - it will test all combinations of the fuzzable elements in a request.  

Thanks,

Marina
