### ISSUE TITLE
Way to specify specific operation for fuzzing

### ISSUE THREAD

**Issue by devikasondhi** [microsoft/restler-fuzzer#269]
Hi,

I have a large spec file for an API containing description of several microservices. I'm interested in testing only a particular operation of a microservice (and its producers). Is there a way I can specify this when executing RESTler?

**Comment by PatGod** [comment]
Hi,

In Test or Fuzz-lean or Fuzz modes, you can use the path_regex option to filter the API paths you are interested in testing. See https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md#path_regex-str-default-noneno-regex-filtering

Example: when invoking restler.exe, add the option 

`--path_regex "(XXX)|(YYY)"`

to test/fuzz only the paths including the strings XXX or YYY. Note that RESTler will also include any other requests that are needed to exercise such requests, that is, it will include producers of resources used in the regex-selected paths (if needed).
