### ISSUE TITLE
Compiler failure has an exit code of 0

### ISSUE THREAD

**Issue by rhtenhove** [microsoft/restler-fuzzer#270]
When `compile` fails, the exit code is 0. This hides problems in a CI pipeline, where the fuzz jobs which depend on compilation would subsequently fail.

For example

```shell
# dotnet /RESTler/restler/Restler.dll compile --api_spec openapi.yml
Starting task Compile...

ERROR: Compiler failed. See logs in /Compile directory for more information.

Task Compile failed.
Collecting logs...
# echo $?
0
```

Tested using docker image `mcr.microsoft.com/restlerfuzzer/restler:v8.0.0`

**Comment by marina-p** [comment]
Thanks for reporting, we will fix this ASAP.
