### ISSUE TITLE
How do I force Restler to try out all different values provided in a custom payload?

### ISSUE THREAD

**Issue by Joris-Kuehl** [microsoft/restler-fuzzer#272]
... or what would be the best practice to achieve something similar, if custom payloads are not intended for this purpose?
I am testing Restler on a very simple CRUD Api for TodoItems <code>(id: Integer, name: String, isComplete: Boolean)</code> and have provided the following custom payload in the dictionary:
<pre><code>"restler_custom_payload": {
  "name": [
    "fuzzstring", "ultrasuperduperannoyinglylongstringwithwhichtofuzz"
  ]
},
</pre></code>

and introduced a very simple bug which I was hoping to "catch" with Restler. Trying to POST or PUT any TodoItem with a name longer than 20 characters returns 501.
After 5 minutes in fuzz mode, Restler only uses the shorter string for any and all requests and thus does not discover the bug. The one exception and only reason I know the custom payload was correctly compiled is that Restler used the second, longer string **once**, in a sequence where it POSTed an item with the short name, deleted it and then tried to PUT an item with the long name at the same id. Resulting in a 404 because the item has been deleted.

If I reverse the order in this list, it will try to POST with the long name, get the 501, create a bug bucket, try the short string and (sensibly) use the short name in all further tests.
I would like to know how I can test each value at least once, without needing to manually order them such that the correct ones come last and whether a custom payload is even the right way to do that.

Thanks,
Joris

**Comment by Joris-Kuehl** [comment]
I just realized the --test_all_combinations flag does what I want, though it only works in Test and Fuzz-Lean modes.
I am keeping the issue open for now because running help or trying to use the flag in Fuzz mode says it only works in Test mode, even though it works perfectly fine in Fuzz-Lean, so that's a very minor documentation error.

**Comment by PatGod** [comment]
@Joris-Kuehl Hi Joris, 

In fuzz mode, RESTler is supposed to try all possible value combinations up to max_combinations per request (by default 20) - see https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md#max_combinations-int-default-20 -- are you sure that limit is not exceeded? 

Yes, test-all-combinations is a new option to force this behavior, that is, trying all value combinations, in test mode (and fuzz-lean mode, which is just test mode with checkers). But it should not be needed in fuzz mode...

**Comment by Joris-Kuehl** [comment]
@PatGod Hi Patrice,
thank you for the reply. I am fairly sure the limit was not exceeded. I have since made some changes. Namely, the error is now triggered by special characters in the name and is a 500 instead of 501. The most recent setup in which i have verified this uses the following dictionary:
<pre><code>{
  "restler_fuzzable_string": [
    "fuzzstring"
  ],
  "restler_fuzzable_string_unquoted": [],
  "restler_fuzzable_datetime": [
    "2019-06-26T20:20:39+00:00"
  ],
  "restler_fuzzable_datetime_unquoted": [],
  "restler_fuzzable_uuid4": [
    "566048da-ed19-4cd3-8e0a-b7e0e1ec4d72"
  ],
  "restler_fuzzable_uuid4_unquoted": [],
  "restler_fuzzable_int": [
    "1"
  ],
  "restler_fuzzable_number": [
    "1.23"
  ],
  "restler_fuzzable_bool": [
    "true"
  ],
  "restler_fuzzable_object": [
    "{ \"fuzz\": false }"
  ],
  "restler_custom_payload": {
    "name": [
      "namestring", "??????????"
    ],
    "isComplete": [
      "true", "false"
    ]
  },
  "restler_custom_payload_unquoted": {},
  "restler_custom_payload_uuid4_suffix": {}
}
</pre></code>

That comes out to a total of 4 combinations for a TodoItem. I have left the settings file at its default max 20 combinations. If I do not add the --test_all_combinations flag, only the combination `(1, "namestring", true)` is used, even in fuzz mode.

Again, the baffling exception in 15 minutes of fuzzing are the two seperate times where Restler posts, deletes and then tries to put a resource and uses the "??????????" name for the put, getting a 404. Outside of this very specific case, it does not touch the other combinations.

Once I do add the flag, all 4 combinations are properly tried out and the bug is found in fuzz-lean mode. Going through the network testing file, Restler also confirms that there are only 4 combinations - the file says combination 1/4, 2/4, etc.

I have only run fuzz mode for between 1 and 15 minutes though, since it's a very simple Api and I was not expecting to find anything anyway. 

Is it possible that Restler does try all combinations, but that is way down on the list of priorities and only happens an hour or two into fuzzing? If it **should** happen near the beginning of the run though, I could send you the full result folders if you like?

**Comment by PatGod** [comment]
@Joris-Kuehl Hi Joris,

Thank you for your detailed report and additional information.

In fuzz mode, I expected RESTler to try all these combinations as soon as it reaches that POST request the first time (that is, early in the search). But perhaps RESTler treats lists of values with 'rester_custom_payload' differently from lists of values with 'restler_fuzzable_*' -- for the latter, it should definitely try all the listed values in fuzz mode (if this is easy for you, you could try extending your dictionary with multiple values for, say, restler_fuzzable_number, and you should see RESTler trying all these values and combinations in fuzz mode).

Maybe @marina-p might know the explanation...

**Comment by Joris-Kuehl** [comment]
I have now tried this dictionary, moving the list of names up to restler_fuzzable_string:

<pre><code>{
  "restler_fuzzable_string": [
    "namestring", "??????????"
  ],
  "restler_fuzzable_string_unquoted": [],
  "restler_fuzzable_datetime": [
    "2019-06-26T20:20:39+00:00"
  ],
  "restler_fuzzable_datetime_unquoted": [],
  "restler_fuzzable_uuid4": [
    "566048da-ed19-4cd3-8e0a-b7e0e1ec4d72"
  ],
  "restler_fuzzable_uuid4_unquoted": [],
  "restler_fuzzable_int": [
    "1"
  ],
  "restler_fuzzable_number": [
    "1.23"
  ],
  "restler_fuzzable_bool": [
    "true"
  ],
  "restler_fuzzable_object": [
    "{ \"fuzz\": false }"
  ],
  "restler_custom_payload": {
    "isComplete": [
      "true"
    ]
  },
  "restler_custom_payload_unquoted": {},
  "restler_custom_payload_uuid4_suffix": {}
}
</pre></code>

The only reason I was using custom payloads instead of restler_fuzzable_XXXX was, because they overwrite the automatically inferred producer consumer dependency between POST and PUT, specifically of the isComplete field (lazy workaround for #271).

The situation remains the same. Restler now detects two combinations (as it should). In test and fuzz-lean, the bug is only found with the --test_all_combinations flag on. Otherwise Restler stops at the first successful combination.

That remains true for fuzz mode, which did not try the second combination at all in 6 minutes of fuzzing (not even the odd POST,DELETE,PUT sequence I mentioned before). Reading the network.testing file, POST was definitely encountered and used successfully dozens of times.

**Comment by PatGod** [comment]
@Joris-Kuehl Hi Joris,

Thanks for confirming. I actually can confirm this behavior with my own tests.

@marina-p To summarize, fuzz mode now behaves like the test (and fuzz-lean) mode: alternate values (specified in the fuzzing dictionary) are now only considered when a request is failing. Isn't this a regression?

(This would also mean we don't have a unit-test that covers this behavior of the fuzz mode, right?)

Bottom-line: this looks like a new RESTler bug (a regression) to me...

**Comment by marina-p** [comment]
@Joris-Kuehl @PatGod Thank you for the detailed description and repro steps!  This sounds like a bug.  The code is supposed to do the same thing in fuzz mode as in testing all combinations:

```python
# line 265 in driver.py
    # bfs needs to be exhaustive to provide full grammar coverage
    elif Settings().fuzzing_mode in ['bfs', 'bfs-fast', 'test-all-combinations']:

        # This loop will iterate over possible remaining renderings of the
        # current sequence.
...
```

(and one of the engine unit tests is supposed to test for this behavior).

I will investigate.

Thanks,

Marina

**Comment by PatGod** [comment]
@marina-p This behavior is actually expected because the 'fuzz' mode currently uses the 'bfs-cheap' search strategy - see line 378 of src/driver/Program.fs (https://github.com/microsoft/restler-fuzzer/blob/d8f73524187330c3d8ca12b749996f40d9a64393/src/driver/Program.fs#L378 

        let fuzzingParameters =
            (getCommonParameters parameters (Some maxDurationHours))
            @
            [
                "--fuzzing_mode bfs-cheap"
            ]

        return! runRestlerEngine workingDirectory fuzzingParameters pythonFilePath
    }

Bfs-cheap is defined in https://patricegodefroid.github.io/public_psfiles/icst2020.pdf and was set as the default in order to explore all the request sequences deeper and faster when using checkers.

To allow users (like @Joris-Kuehl) to force RESTler to explore all renderings in every state (bfs) or to explore all renderings only when visiting a new state for the first time (bfs-fast), the main driver restler.exe, defined in Program.fs, should be extended to let the user overwrite the default search strategy (bfs-cheap) by either **bfs** or **bfs-fast** *in fuzz mode* only. OK?

**Comment by PatGod** [comment]
@marina-p I have just assigned this item to myself and will take care of it.

I suggest the following changes: 
- in fuzz mode, let's bfs-fast become the default-search strategy.
- let's add a new 'search-strategy' option to the main driver restler.exe where the user can instead select bfs or bfs-cheap.

(Note: historically, bfs-cheap become the default search strategy in fuzz mode after the checkers were available but **before** the new fuzz-lean mode was available: fuzz with bfs-cheap is indeed closest to fuzz-lean, compared to bfs or bfs-fast.)

**Comment by marina-p** [comment]
@PatGod Sounds good.  Thank you!

(I believe it's implied by the above but just in case: from the driver, the new search strategy should work just for Fuzz mode, not Fuzz-Lean)

**Comment by PatGod** [comment]
@Joris-Kuehl PR #288 will set the new default search-strategy to bfs-fast in fuzz mode and will enumerate all the values you specified in your directory as you expected. 

This PR will be merged shortly and will close this issue. 

Let us know if you have any other comments. Thanks (and sorry for the delay...)!
