### ISSUE TITLE
grammar.py does not exist.

### ISSUE THREAD

**Issue by higher75** [microsoft/restler-fuzzer#323]
ubuntu18.04 
python3.8

ERROR: The RESTler grammar file path Compile/grammar.py does not exist.

**Comment by higher75** [comment]
can you help me? thank you

**Comment by mbiuki** [comment]
Are you compiling with RESTler command? Can you describe the steps?

**Comment by higher75** [comment]
Hi. i do these

$ mkdir restler_bin
$ git clone https://github.com/microsoft/restler-fuzzer.git
$ python3.8 ./build-restler.py --dest_dir <Full Path for restler_bin dir>

then 

$ cd restler_bin
compiler    engine    restler     resultsAnalyzer
$ cd restler/Compile       --------------------> The grammar.py does not exist.
config.json    defaultDict.json    preprocessed     restler-20210831-063220.log    StdErr.txt     StdOut.txt

last I go back to the restler_fuzzer_main directory 
$ python3.8 restler-quick-start.py --api_spec_path <Full path to openapi.yml>  --restler_drop_dir <Full path to restler_bin dir>
ERROR: The RESTler grammar file path Compile/grammar.py does not exist

**Comment by higher75** [comment]
python3.8 restler-quick-start.py --api_spec_path  <Full path to openapi.yml>   --restler_drop_dir  <Full path to restler_bin dir>

**Comment by higher75** [comment]
thanks you!
