### ISSUE TITLE
RESTler should resolve additionalProperties

### ISSUE THREAD

**Issue by c7h** [microsoft/restler-fuzzer#330]
Hi, I have an OpenAPI specification containing $ref  in _additionalProperties_. Following is a simplified version of my swagger spec file (The original can be found here https://github.com/free5gc/Nnrf_NFManagement/blob/master/api/openapi.yaml)

```yaml
#...
components:
  schemas:
    NrfInfo:
      properties:
        servedUdrInfo:
          additionalProperties:
            $ref: '#/components/schemas/UdrInfo'
          minProperties: 1
          type: object
#...
components:
  schemas:
    UdrInfo:
      example:
        supportedDataSets:
        - null
        - null
        groupId: groupId
        externalGroupIdentifiersRanges:
        - start: start
          pattern: pattern
          end: end
        - start: start
          pattern: pattern
          end: end
        supiRanges:
        - start: start
          pattern: pattern
          end: end
        - start: start
          pattern: pattern
          end: end
        gpsiRanges:
        - start: start
          pattern: pattern
          end: end
        - start: start
          pattern: pattern
          end: end
      properties:
        groupId:
          type: string
        supiRanges:
          items:
            $ref: '#/components/schemas/SupiRange'
          minItems: 1
          type: array
        gpsiRanges:
          items:
            $ref: '#/components/schemas/IdentityRange'
          minItems: 1
          type: array
        externalGroupIdentifiersRanges:
          items:
            $ref: '#/components/schemas/IdentityRange'
          minItems: 1
          type: array
        supportedDataSets:
          items:
            $ref: '#/components/schemas/DataSetId'
          minItems: 1
          type: array
      type: object
#...
```

After compiling, the servedUdrInfo is rendered as fuzzable_object instead of an UdrInfo Object:

`"servedUdrInfo\":{ \"fuzz\": false }`

If I resolve the $ref manually, it seems to work.

My question is now: Does RESTler resolve the $ref for additionalProperties?

**Comment by marina-p** [comment]
Hello @c7h,

RESTler does not support additionalProperties right now. It just skips them, and then assigns the default object.   

I'll change this issue to 'ehnancement'.  In the meantime, the workaround is as you have done, to reference these properties directly instead of via 'additionalProperties'.

Thanks,

Marina

**Comment by mbrg** [comment]
Hi @marina-p :)

+1 on this ask

In our case, the keys of the object are arbitrary strings, and the values need to compily with a referenced schema. Here is the relevant part of the API spec:

```json
"/configurations/integration/{integration_id}": {
  "put": {
     "requestBody": {
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "additionalProperties": {
                "$ref": "#/components/schemas/PolicyConfigurationProperties"
              }
            }
          }
        },
        "required": true
      }
    }
  }
```

**Comment by hidingturtle** [comment]
Hi @c7h,

could you share your version of the yaml-file where you resolved the $refs manually? When I do it, the compilation still does not work.

**Comment by marina-p** [comment]
Hello @hidingturtle,

Could you please try out the update 'mp/330' branch and let me know if this fully addresses your issue with additionalProperties?  

Thanks,

Marina

**Comment by hidingturtle** [comment]
Hello @marina-p,
I tried it out and it addresses my issue with additionalProperties! Thank you 😄 
servedUdrInfo is now getting rendered as it is specified by the OpenAPI specification instead of the default object.

**Comment by marina-p** [comment]
Hello @hidingturtle,

Great, thanks for trying it out.  This will be merged shortly.

Thanks,

Marina
