### ISSUE TITLE
Question regarding the use of unrequired parameters in fuzzing mode

### ISSUE THREAD

**Issue by JuanCarlosAlonsoValenzuela** [microsoft/restler-fuzzer#395]
Hello, thanks for the great tool.

I am currently trying to test one of the operations of this API by using RESTler: https://developer.deutschebahn.com/store/apis/info?name=StaDa-Station_Data&version=v2&provider=DBOpenData#!/default/get_stations, specifically, the operation “/stations”, a “GET” operation used to retrieve information about stations.

I have two doubts about RESTler:

1)	On the first place, this operation receives 8 parameters, with none of them being required but, when executing RESTler in fuzzing mode, it only generates requests containing all of them, resulting in a total of 14 possible combinations given the dict.json that I provided to RESTler. Is there any way of telling RESTler to try to omit unrequired parameters when fuzzing the API?

2)	I set the value “AllowGetProducers” of the config.json file to true, but RESTler does not reuse any values of the provided by the API responses. Does this happen because the test sequences are always of length 1?
 My experiment configuration and the results returned by the fuzzing mode of RESTler can be found here: https://drive.google.com/file/d/1lfx6Ks02gPBcq10QgtSZnWjcpE9xEpBe/view?usp=sharing

**Comment by marina-p** [comment]
Hello @JuanCarlosAlonsoValenzuela,

1. Yes.  Question: do you want to not test any optional parameters at all, or do you want to actually fuzz some of them?  

   You can control which query (and header) parameters are passed through the ```param_combinations``` setting in the engine settings file.  Here is an example configuration that will pass all the required parameters, and "all combinations of optional parameters up to the 'max_combinations' bound".   This starts with "all required parameters" + "no optional parameters", then "all required parameters" + "1-combinations of optional parameters", etc.  So, you can set the ```max_combinations``` bound in this setting to "1", and it will stop and never get to "1-combinations of optional parameters".  

```
"test_combinations_settings": {
     "query_param_combinations": {
      "max_combinations": 1,
      "param_kind": "optional"
    }
}

```

2. This could be caused by several things - can you please provide one example of a value that you'd like to be re-used, and which parameter in which endpoint+method it should be assigned to?  That would help narrow down the issue.

Thanks,

Marina

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Hello @marina-p and thank you for your quick response.

1) I want to fuzz some of them (i.e., generate requests containing all the optional parameters, requests containing a subset, and request that do not contain any optional parameter). I think that I understood your response, but I still do not completely understand the meaning of the “max_combinations” parameter. According to the docs (https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md), this parameter is used to specify the maximum number of parameter value combinations for parameters within a given request payload.
In the configuration shown in your code excerpt (max_combinations=1), would the total number of API request be 2? (i.e., one API request containing only required parameters and one request containing some optional parameters). 

2) After reading the docs again, I think that maybe the producer-consumer dependencies may be out-of-scope in this case, since they seem to be intended for testing sequences of operations, and in my configuration, I am only testing sequences of length 1 (Since I am only testing the “/station” operation).

In this case, I have used the default configuration for the input parameter “federalstate” (i.e., the value “fuzzstring”). By setting the value of “allowGetProducers” to true, I expected RESTler to automatically associate this input field with the response field “result.federalState” (Note that, in the response, federalState is in camelCase). I think that this did not happen because I am only testing the “/stations” operation, maybe if there was another operation that received “federalState” as an input, RESTler could automatically associate the field in the output of “/station” (Producer) to the input of this new operation (Consumer).

**Comment by marina-p** [comment]
1. There are two places ```max_combinations``` are used, and the meaning is a bit different.   The top-level ```max_combinations``` means what you stated above - it is an upper bound that applies to all the possible combinations of all parameters tested for the entire request.   The ```max_combinations``` inside of the ```*_param_combinations``` only applies to the schema combinations for that particular parameter.  When the latter value is set to "1", just one "schema combination" of query parameter combinations will be tested - the combination "all required and zero optional parameters".   

2. Thank you, this is helpful and that's correct, with multiple methods it would work but today RESTler does not support this particular case where a particular request (endpoint, method) can consume the return values of its own response in its input parameters.  This is in the backlog and is related to item #286.  

Thanks,

Marina

**Comment by marina-p** [comment]
Related fix: #399

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Thank you for your response. I reconfigured RESTler and now it works as I expected.

Thanks,

Juan Carlos

**Comment by marina-p** [comment]
Great, thanks for confirming.  Closing the issue.
