### ISSUE TITLE
Provide option to output task logs into a specific directory

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#406]
This should be specified on the command line, e.g.:

```restler.exe --output_log_dir  <directory>```

**Comment by rreexxllii0310** [comment]
Hello @marina-p,

How to use this command `--output_log_dir <directory>`?
thank you.

**Comment by rreexxllii0310** [comment]
I saw that `[--workingDirPath <local logs directory (default: cwd)>]`.
Can this command change the output dir of `RestlerLogs` after compile?
If not, how can I change the output dir of `RestlerLogs` without using `os.chdir()` to change the cwd?
Is this what `--output_log_dir <directory>` does?

Thank you!

**Comment by marina-p** [comment]
Hello @rreexxllii0310, 
```--workingDirPath``` does not affect ```RestlerLogs``` today.  I'll go ahead and get this fixed.

Thanks,

Marina
