### ISSUE TITLE
Compile with config.json got error

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#434]
Yes.  When you compile, you should specify the above dictionary (via the config.json - restler.exe compile <path to config.json>), which includes the custom payload you added above.  The compiler will read all the custom payloads in the dictionary and generate the corresponding grammar primitives.

_Originally posted by @marina-p in https://github.com/microsoft/restler-fuzzer/issues/197#issuecomment-832898724_

Hi, I've tried the config.json to automatically generate custom payloads in dict.json and grammar.py.
But I got an error while compiling by `./Restler compile config.json`.

My two specifications are under `/restler_bin/restler/spec` dir

My config.json is under `/restler_bin/restler`:
```
1 {
2    "SwaggerSpecConfig": [
3        {
4             "SpecFilePath": "/spec/iottalkv1_ccm_api_swagger2.0_20210328.yaml",
5             "DictionaryFilePath": "ccm_dict.json"
6        },
7        {
8             "SpecFilePath": "/spec/iottalkv1_csm_api_swagger2.0_20210329.yaml",
9             "DictionaryFilePath": "csm_dict.json",
10            "Dictionary": {
11                "restler_custom_payload": {
12                    "min_max": ["[[1, 1]]", "[[1, 2]]", "[[3, 4]]", "[[1, 10]]"]
13                }
14            }
15        }
16     ]
17 }
```

The error is as following:
```
ERROR: Invalid format for compiler config file config.json. Please refer to the documentation for the compiler config file format.

ERROR: Deserialization exception: "An exception occurred during deserialization: Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path '', line 10, position 27."
```

How can I solve it??
Thank you !

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

Apologies for the delay.   

This is due to a bug in our documentation.  The "Dictionary" field is a string rather than an object type, so it has to be specified as below (note, you can specify either the ```DictionaryFilePath``` or an inlined ```Dictionary``` but not both - the error is not very clear, we will update this as well).  

Thanks,

Marina

```json
 {
    "SwaggerSpecConfig": [
        {
            "SpecFilePath": "d:\\git\\restler-fuzzer\\demo_server\\swagger.json",
           "Dictionary": "{\"restler_custom_payload\": { \"min_max\": [\"[[1, 1]]\", \"[[1, 2]]\", \"[[3, 4]]\", \"[[1, 10]]\"]}}"
        }
     ]
}
```

**Comment by rreexxllii0310** [comment]
@marina-p 
Thanks for replying!
I'll try it later.

**Comment by rreexxllii0310** [comment]
@marina-p 
Hi, I've tried to use config.json to compile.
But, I got task failed error:
`ERROR: Compiler failed. See logs in /home/rex/restler_bin/restler/Compile directory for more information.`

I saw **restler-20220117-121013.log** in Compile directory:
```
Restler Information: 0 : Starting task Compile...
    DateTime=2022-01-16T16:10:14.0670826Z
Restler Information: 0 : Launching 'dotnet "/home/rex/restler_bin/restler/../compiler/Restler.CompilerExe.dll" "/home/rex/restler_bin/restler/Compile/config.json"'
    DateTime=2022-01-16T16:10:14.1496358Z
Restler Information: 0 : Process execution terminated in 00:00:00.8963547 with exit code 0x86: 'dotnet "/home/rex/restler_bin/restler/../compiler/Restler.CompilerExe.dll" "/home/rex/restler_bin/restler/Compile/config.json"'
    DateTime=2022-01-16T16:10:15.0499205Z
Restler Information: 0 : (207) dotnet "/home/rex/restler_bin/restler/../compiler/Restler.CompilerExe.dll" "/home/rex/restler_bin/restler/Compile/config.json" exited with code: 134
    DateTime=2022-01-16T16:10:15.0539154Z
Restler Error: 0 : Compiler failed. See logs in /home/rex/restler_bin/restler/Compile directory for more information.
    DateTime=2022-01-16T16:10:15.0591940Z
Restler Information: 0 : Task Compile failed.
    DateTime=2022-01-16T16:10:15.0614573Z
Restler Information: 0 : Collecting logs...
    DateTime=2022-01-16T16:10:15.0648925Z
```

Could you help me?
Thank you!

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

Could you please share the output in Compile\StdErr.txt, and the last few lines of Compile\StdOut.txt?

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p,

I saw the error in StdErr.txt, and I found the error was produced since I have two **SpecFilePath** with two different specs.
So, I tried to delete one of them, and It successed.
Is there any method to compile two specs at once?

Thank you!

**Comment by marina-p** [comment]
@rreexxllii0310 

Yes, they should be placed in an array as follows (see CompilerConfig.md)

```
"SwaggerSpecFilePath": [ "spec1.json", "spec2.json"]

```

**Comment by rreexxllii0310** [comment]
@marina-p
Thank you!
