### ISSUE TITLE
Resources to avoid deleting

### ISSUE THREAD

**Issue by mbrg** [microsoft/restler-fuzzer#443]
Hi there,
I'm pre-provisioning a few resources before fuzzing because they require some time to fully set up. I would like to specify that these resources should not be deleted, I.e. don't call a certain combination of (endpoint, method, parameters). Is there any easy way to achieve that with configuration files?

**Comment by PatGod** [comment]
@mbrg Hi Michael, good to hear from you! ;-)

You can use the option --path_regex to specify the request types you want to skip when running RESTler in test, fuzz-lean, or fuzz modes -- see the doc https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md for this option.

(For resource creations that are easy to invoke with RESTler and part of the API/service you want to test/fuzz but are long to execute, please have a look at the create_once option - that might also be of interest to you, unless the pre-provisioned resources are not part of the API/service you want to fuzz.)

Cheers,

Patrice

**Comment by mbrg** [comment]
Hi Patrice! Good to hear from you too :)

Thank you. The create_once option is is exactly what I needed. It's the same API, but it takes some time for background processing to create a few other resources I want to fuzz too.
