### ISSUE TITLE
Question: How to determine if the smoketest is successful

### ISSUE THREAD

**Issue by divyakrishnankutty** [microsoft/restler-fuzzer#459]
Hello,

Here is the smoketest result, It says 'Task Test succeeded.'. However, successful is 0 for Request coverage. What does this imply? 
Am I missing anything here?

api_fuzztesting_test# ../restler_bin_test/restler/Restler test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings Compile/engine_settings.json --no_ssl
Starting task Test...
Using python: 'python3' (Python 3.8.10)
Request coverage (successful / total): 0 / 18
No bugs were found.
Task Test succeeded.
Collecting logs...

**Logs for the test**

Restler Information: 0 : Starting task Test...
    DateTime=2022-02-03T13:29:38.6141101Z
Restler Information: 0 : Launching 'python3 --version'
    DateTime=2022-02-03T13:29:38.6639873Z
Restler Information: 0 : Launching 'python --version'
    DateTime=2022-02-03T13:29:38.6646175Z
Restler Information: 0 : Process execution terminated in 00:00:00.0182669 with exit code 0x0: 'python3 --version'
    DateTime=2022-02-03T13:29:38.6890139Z
Restler Information: 0 : (17767) python3 --version exited with code: 0
    DateTime=2022-02-03T13:29:38.6945441Z
Restler Information: 0 : Launching 'python3 -B "/home/divya/demo/restler_bin_test/restler/../engine/restler.py" --restler_grammar "/home/divya/demo/api_fuzztesting_test/Compile/grammar.py" --custom_mutations "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --set_version 8.3.0    --no_ssl   --settings "/home/divya/demo/api_fuzztesting_test/Compile/engine_settings.json"     --include_user_agent --no_tokens_in_logs t --garbage_collection_interval 30 --fuzzing_mode directed-smoke-test'
    DateTime=2022-02-03T13:29:38.7032263Z
Restler Information: 0 : Process execution terminated in 00:00:00.2348094 with exit code 0x0: 'python3 -B "/home/divya/demo/restler_bin_test/restler/../engine/restler.py" --restler_grammar "/home/divya/demo/api_fuzztesting_test/Compile/grammar.py" --custom_mutations "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --set_version 8.3.0    --no_ssl   --settings "/home/divya/demo/api_fuzztesting_test/Compile/engine_settings.json"     --include_user_agent --no_tokens_in_logs t --garbage_collection_interval 30 --fuzzing_mode directed-smoke-test'
    DateTime=2022-02-03T13:29:38.9381866Z
Restler Information: 0 : (17770) python3 -B "/home/divya/demo/restler_bin_test/restler/../engine/restler.py" --restler_grammar "/home/divya/demo/api_fuzztesting_test/Compile/grammar.py" --custom_mutations "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --set_version 8.3.0    --no_ssl   --settings "/home/divya/demo/api_fuzztesting_test/Compile/engine_settings.json"     --include_user_agent --no_tokens_in_logs t --garbage_collection_interval 30 --fuzzing_mode directed-smoke-test exited with code: 0
    DateTime=2022-02-03T13:29:38.9389040Z
Restler Information: 0 : Launching 'dotnet "/home/divya/demo/restler_bin_test/restler/../resultsAnalyzer/Restler.ResultsAnalyzer.dll" analyze "/home/divya/demo/api_fuzztesting_test/Test" --output_dir "/home/divya/demo/api_fuzztesting_test/Test/ResponseBuckets" --dictionary_file "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --max_instances_per_bucket 10'
    DateTime=2022-02-03T13:29:38.9464315Z
Restler Information: 0 : Process execution terminated in 00:00:00.3391893 with exit code 0x0: 'dotnet "/home/divya/demo/restler_bin_test/restler/../resultsAnalyzer/Restler.ResultsAnalyzer.dll" analyze "/home/divya/demo/api_fuzztesting_test/Test" --output_dir "/home/divya/demo/api_fuzztesting_test/Test/ResponseBuckets" --dictionary_file "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --max_instances_per_bucket 10'
    DateTime=2022-02-03T13:29:39.2857095Z
Restler Information: 0 : (17774) dotnet "/home/divya/demo/restler_bin_test/restler/../resultsAnalyzer/Restler.ResultsAnalyzer.dll" analyze "/home/divya/demo/api_fuzztesting_test/Test" --output_dir "/home/divya/demo/api_fuzztesting_test/Test/ResponseBuckets" --dictionary_file "/home/divya/demo/api_fuzztesting_test/Compile/dict.json" --max_instances_per_bucket 10 exited with code: 0
    DateTime=2022-02-03T13:29:39.2862940Z
Restler Information: 0 : Request coverage (successful / total): 0 / 18
    DateTime=2022-02-03T13:29:39.4041008Z
Restler Information: 0 : No bugs were found.
    DateTime=2022-02-03T13:29:39.4058720Z
Restler Information: 0 : Task Test succeeded.
    DateTime=2022-02-03T13:29:39.4093387Z
Restler Information: 0 : Collecting logs...
    DateTime=2022-02-03T13:29:39.4119789Z

**Comment by PatGod** [comment]
It just means that your current API coverage is terrible. You need to investigate further and look at the network logs generated by RESTler. Please see the docs, in particular https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/ImprovingCoverage.md

**Comment by divyakrishnankutty** [comment]
Thank you that helped! I was't giving proper host details.
