### ISSUE TITLE
Question: How to provide multiple values in dict.json

### ISSUE THREAD

**Issue by divyakrishnankutty** [microsoft/restler-fuzzer#468]
Hi,

While running smoketest, having problem with some of the APIs.
For example, I have given this in dict.json, "restler_fuzzable_string": ["test1"].

Now, many of my API parameters are expecting multiple fuzzable_string and each of them takes value as 'test1'. Similarly, for restler_fuzzable_int, each fuzzable_int takes same value. 

To elaborate, my API expects something like this:

It expects parameters in this manner,  fuzzable_string(1st param), fuzzable_string(4th param), fuzzable_string(5th param), fuzzable_int(2nd param), fuzzable_int(3rd param).

Need each of them to have a different value, how can I achieve this?

**Comment by marina-p** [comment]
Hello @divyakrishnankutty,

To specify values for a particular parameter, you can use ```restler_custom_payload``` (for details, see [FuzzingDictionary.md](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/FuzzingDictionary.md)).  After you specify these in the dictionary, re-compile the spec and reference the new dictionary in config.json.  Then, RESTler will only test each parameter with the values specified in the custom payload in the dictionary.

Thanks,

Marina

**Comment by divyakrishnankutty** [comment]
It worked after using restler_custom_payload. Thank you @marina-p!
