### ISSUE TITLE
[Question] How to generate fuzzable string randomly?

### ISSUE THREAD

**Issue by sqli0189** [microsoft/restler-fuzzer#504]
Hi,

In our request payloads, for some fields, their value must be unique. I know currently, I can add more customized fuzz string values by updating **Compile/dict.json** like below:

```  
.......
"restler_fuzzable_string": [
    "fuzzstring", "fuzzstring1", "fuzzstring2", "fuzzstring3", "fuzzstring4"
  ],
......
```

I am wondering if there is a way to generate fuzz string randomly? For example, writing a Python script that generates fuzz string randomly and pass the random value to the restler while running fuzz test. I searched user guides but haven't find any examples about that.

**Comment by marina-p** [comment]
Hello @sqli0189,

Yes, you can provide a Python function that will generate the fuzzable strings randomly.  See the ```custom_value_generators``` setting in [SettingsFile.md](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md) - basically, you provide a similar dictionary to the one in ```Compile/dict.json``` in a Python file with the values as functions instead of lists (there is also already a template generated in the ```Compile``` folder, similar to the default dictionary).  The custom value generator will override the dictionary property, so you do not need to remove it from the dictionary.

This is a recently added feature, so please let us know if there are improvements we can make to the documentation or if you run into any issues.

Thanks,

Marina

**Comment by sqli0189** [comment]
Thanks for your reply on this. I followed the instruction in  [SettingsFile.md](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md), I created a py file to generate fuzzable string randomly, but there is an exception thrown as below when I execute the fuzz test:

`Initializing: Garbage collection every 30 seconds.
2022-04-03 14:52:32.708: Generation: 1 
Exception 'function' object is not iterable applying checker <checkers.payload_body_checker.PayloadBodyChecker object at 0x104b97c40>
Terminating garbage collection. Waiting for max 300 seconds.
Traceback (most recent call last):
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/fuzzer.py", line 42, in run
    self._num_total_sequences = driver.generate_sequences(
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 700, in generate_sequences
    seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 322, in render_sequential
    valid_renderings = render_one(seq_collection[ith], ith, checkers, generation, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 214, in render_one
    apply_checkers(checkers, renderings, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/engine/core/driver.py", line 150, in apply_checkers
    checker.apply(renderings, global_lock)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/checkers/payload_body_checker.py", line 185, in apply
    self._run_feedback_fuzzing(last_request, body_schema_list)
  File "/Users/alex/workspace/restler-fuzzer/restler_bin/engine/checkers/payload_body_checker.py", line 622, in _run_feedback_fuzzing
    ignore = set(
TypeError: 'function' object is not iterable`

**Comment by marina-p** [comment]
Hi @sqli0189,

Your implementation is correct, the above is a bug in RESTler.  This will be fixed early next week.

A workaround is to disable the payload body checker on the command line (```--disable_checkers payloadbody```), this way you can still fuzz using all of the other checkers.

Thanks,

Marina

**Comment by marina-p** [comment]
@sqli0189 the fix is now merged.

Please let me know if you see any other issues with your usage of the dynamic value generators.

Thanks,

Marina

**Comment by sqli0189** [comment]
Yes, it works
