### ISSUE TITLE
Restler Engine Failed

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#511]
Hello,
I'm using Oauth to test my system with the output by following:
![image](https://user-images.githubusercontent.com/40860137/163317893-eee04d76-6d96-46e2-868c-b4848c565275.png)

However, when I use test engine, the successful request coverage is zero:
![image](https://user-images.githubusercontent.com/40860137/163317996-0cabbcba-8611-40a4-a9e3-950b6de1f3c9.png)

In Additions, the network-testing log in Test Folder gives:
![image](https://user-images.githubusercontent.com/40860137/163318186-3a9b4ba7-baf4-42ce-aab6-698ae34dc635.png)

My oauth_token.py looks like this:
![image](https://user-images.githubusercontent.com/40860137/163318372-de516e73-a6f9-4154-a5a9-7a31072e6862.png)

I cannot find the error.
Thanks for help!

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

Does it resolve the issue if you add the full path to python to your command line?  

```--token_refresh_command "<full path to python> /restler_bin/restler/tokenfiles/oauth_token.py"```

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p,
I have tried the full path with:
`/home/rex/restler_bin/restler/tokenfiles/oauth_token.py`

But it still got error
![image](https://user-images.githubusercontent.com/40860137/163332753-0abaf3cd-7b48-40f5-9ee3-cdbe3b45627c.png)

**Comment by marina-p** [comment]
Hello,

The command line you showed above does not have the python executable in it.  Could you please try adding it?

```/usr/bin/python3 /home/rex/restler_bin/restler/tokenfiles/oauth_token.py  ```

**Comment by rreexxllii0310** [comment]
Hello @marina-p,
It works with
`--token_refresh_command "/usr/bin/python3 /home/rex/restler_bin/restler/tokenfiles/oauth_token.py"`

Thanks for helping!

**Comment by rreexxllii0310** [comment]
Hello,
I experienced the issued again.
![image](https://user-images.githubusercontent.com/40860137/163544977-05c1d77a-47ce-46a7-8386-4cb964cf1b65.png)

I think something is wrong after I changed the workingDirPath with comilation.

**Comment by rreexxllii0310** [comment]
It seems to be the connection problem, I can use my token.py to test.

Besides, I also eager to know how to check if RESTler has correctly sent the request with token.

I test with `./Restler test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --no_ssl --token_refresh_command "/usr/bin/python3 /home/rex/restler_bin/restler/tokenfiles/oauth_token.py" --token_refresh_interval 720`
got 301 response status code
![image](https://user-images.githubusercontent.com/40860137/163665361-537e87e5-4c7f-4451-bcae-2cbc2989eb5b.png)

However, when I tried to use postman to send the request with basic authorization, it got 200
![image](https://user-images.githubusercontent.com/40860137/163665403-318040b1-3d4f-4aec-a575-0b8e13975a62.png)

**Comment by rreexxllii0310** [comment]
Hello,
    I gave up to use the previous method, and tried to use cookie to login to test api, since my application didn't support for using token to login.

I set up the cookies in restler_custom_payload_header in dict.json, and compiled with the config.json:
config.json:
```
{
    "SwaggerSpecFilePath": [
        "../specification/scratchtalk.yaml"
    ],
    "CustomDictionaryFilePath": "dict.json"
}
```
 
dict.json:
```
{
    "restler_fuzzable_string": [
        "fuzzstring"
    ],
    "restler_fuzzable_string_unquoted": [],
    "restler_fuzzable_datetime": [
        "2019-06-26T20:20:39+00:00"
    ],
    "restler_fuzzable_datetime_unquoted": [],
    "restler_fuzzable_uuid4": [
        "566048da-ed19-4cd3-8e0a-b7e0e1ec4d72"
    ],
    "restler_fuzzable_uuid4_unquoted": [],
    "restler_fuzzable_int": [
        "1"
    ],
    "restler_fuzzable_number": [
        "1.23"
    ],
    "restler_fuzzable_bool": [
        "true"
    ],
    "restler_fuzzable_object": [
        "{ \"fuzz\": false }"
    ],
    "restler_custom_payload": {},
    "restler_custom_payload_unquoted": {},
    "restler_custom_payload_uuid4_suffix": {},
    "restler_custom_payload_header": {
        "Cookie": [
            "connect.sid=s%3AhtPfx_JPbdCJKI-6_gGmktUciAXgLl51.YjCkK0Eh4PGPwCpxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ]
    }
}
```

Then the grammar.py looks like:
![image](https://user-images.githubusercontent.com/40860137/163984217-a26e80d3-8e68-4c4a-a9ea-d2dc8117283e.png)


However, when I tried to test, it failed and got this error in EngineStdErr.txt:
![image](https://user-images.githubusercontent.com/40860137/163984414-e26f7893-0e96-43fc-892f-932471b6a0c8.png)

How can I solve it?
Thank you!

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

I cannot tell from the above why you are getting this error.  Which version of RESTler are you using?    Is this error only present if you add the custom payload with the cookie to the dictionary?

Thanks,

Marina
