### ISSUE TITLE
Is it possible to change compile/fuzz output sub-directory with settings?

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#512]
Hello,

I'm trying to change the output directory of compiled files and the output directory of Fuzz bug reports,
but I suspect there is no optional settings for change this.

Is there any suggestion to do this? 
Thank you!

**Comment by marina-p** [comment]
Hello @rreexxllii0310, 

There is an output to output the entire task directory to a specific directory:

```restler --workingDirPath <local logs directory> ...```

Is this what you are looking for?

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p,

I think it is what I am seeking.

However, I tried to use it with:
![image](https://user-images.githubusercontent.com/40860137/163516135-01ce6991-ceda-4f0a-b418-984a774c0596.png)

It seems to fail.
What is the problem?

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

You need to specify the full command line you did previously, plus add the ```--workingDirPath path``` in front of it.  The above just has the workingDirPath, without the following ```compile ...```.  

That said, the above exception is a bug.  I will open a separate issue on it.

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p,

I tried to compile a spec and output the files to my desire directory. By:
`./Restler compile --api_spec spec/scratchtalk.yaml --workingDirPath Compile_20220415_1`

It successes.

However, when I tried to do the same thing that outputs the test result to my desire directory. By
`./Restler fuzz --grammar_file Compile_20220415_1/Compile/grammar.py --dictionary_file Compile_20220415_1/Compile/dict.json --no_ssl --token_refresh_command "/usr/bin/python3 /home/rex/restler_bin/restler/tokenfiles/oauth_token.py" --token_refresh_interval 720 --workingDirPath Fuzz_20220415_1`

It gives `ERROR: Invalid argument: --workingDirPath`

Is that possible to change the Fuzz testing result output dir?

**Comment by marina-p** [comment]
Could you please try moving the ```workingDirPath``` argument to before the task argument?  So, ```restler --workingDirPath Compile_2022 compile --api_spec ...```

Apologies for the confusion, the first ```compile``` command line should have been rejected with a better error message in your commands above (this is related to the first bug you hit).

**Comment by rreexxllii0310** [comment]
Hello marina-p.
It works with `restler --workingDirPath Compile_2022 {compile/test/fuzz ...}`

Thank you for answering!
