### ISSUE TITLE
RESTler Test Failed

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#525]
Hello,

I set up the cookies in restler_custom_payload_header in dict.json, and compiled with the config.json:
config.json:

```
{
    "SwaggerSpecFilePath": [
        "../specification/scratchtalk.yaml"
    ],
    "CustomDictionaryFilePath": "dict.json"
}

```

dict.json:

```
{
    "restler_fuzzable_string": [
        "fuzzstring"
    ],
    "restler_fuzzable_string_unquoted": [],
    "restler_fuzzable_datetime": [
        "2019-06-26T20:20:39+00:00"
    ],
    "restler_fuzzable_datetime_unquoted": [],
    "restler_fuzzable_uuid4": [
        "566048da-ed19-4cd3-8e0a-b7e0e1ec4d72"
    ],
    "restler_fuzzable_uuid4_unquoted": [],
    "restler_fuzzable_int": [
        "1"
    ],
    "restler_fuzzable_number": [
        "1.23"
    ],
    "restler_fuzzable_bool": [
        "true"
    ],
    "restler_fuzzable_object": [
        "{ \"fuzz\": false }"
    ],
    "restler_custom_payload": {},
    "restler_custom_payload_unquoted": {},
    "restler_custom_payload_uuid4_suffix": {},
    "restler_custom_payload_header": {
        "Cookie": [
            "connect.sid=s%3AhtPfx_JPbdCJKI-6_gGmktUciAXgLl51.YjCkK0Eh4PGPwCpxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        ]
    }
}
```
Then the grammar.py looks like:
![image](https://user-images.githubusercontent.com/40860137/164155092-612da173-33e3-4847-bd64-ab18e50a1278.png)

However, when I tried to test, it failed and got this error in EngineStdErr.txt:
![image](https://user-images.githubusercontent.com/40860137/164155211-e797e63b-49f8-49a2-b86a-779fc8a59261.png)

How can I solve it?
Thank you!

**Comment by marina-p** [comment]
[Thanks for opening the new issue, copying my response here]
Hello @rreexxllii0310,

I cannot tell from the above why you are getting this error. Which version of RESTler are you using? Is this error only present if you add the custom payload with the cookie to the dictionary?

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p,
1. I use the latest version of main.
2. Even though I remove the `    "restler_custom_payload_header": {
        "Cookie": [
            "connect.sid=s%3AhtPfx_JPbdCJKI-6_gGmktUciAXgLl51.YjCkK0Eh4PGPwCpdnhPpenmxxxxxxxxxxxxxxxxxxxxxxxxx"
        ]
    }` in the dict.json, and recompiled it by `./Restler compile config.json`, and test the grammar.py and dict.json in Compile dir by `./Restler test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json`, it still got the same error.

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

Ok, thank you for confirming.  Could you please see if the resolution in the discussion of #129 helps resolve the issue?  

Thanks,

**Comment by rreexxllii0310** [comment]
Hello @marina-p,
I tried the method in #129, it seems to resolve the issue.
Thanks a lot!
