### ISSUE TITLE
What is the upper bound and lower bound limitation of max_combinations?

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#529]
The default max_combinations in test engine settings is 20.  
Is there any maximal number and is the minimal number 1?

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

The default is 20, min=0, and there is no maximum defined.

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Thank you for applied!
