### ISSUE TITLE
How to test APIs with a CSRF Protected system?

### ISSUE THREAD

**Issue by rreexxllii0310** [microsoft/restler-fuzzer#548]
Hi,
    I've tested my system with restler-fuzzer,
however, the test result comes with much http status code 400.
All of the 400 are due to "CSRF token is missing".
![image](https://user-images.githubusercontent.com/40860137/174329211-cb4e1040-89f9-4ccc-a48d-d7989b3e44ef.png)

Is there any method to test a system which has CSRF Protect?
Thanks.

**Comment by marina-p** [comment]
Hello @rreexxllii0310,

For any construct that is not included in the OpenAPI spec, you will need to inject it by specifying it manually in the dictionary (and possibly also via ```custom_value_generators```, depending on your requirement - see SettingsFile.md for details).

The exact answer to your question depends on the format in which your API expects this token.  For example, if it is in a header, adding the following to your dictionary will inject the below header for every request.

```"restler_custom_payload_header": {
   "headerName": ["headerValue1", "headerValue2"] 
}
```

It gets a bit cumbersome if you only need the header to be injected into some of the requests.  This can be done with *per resource settings* (see SettingsFile.md).  

Can you share more details about the specific CSRF protection implementation of your API?

Thanks,

Marina

**Comment by rreexxllii0310** [comment]
Hello @marina-p ,
Thank you for applying.

The System is using `from flask_wtf.csrf import CSRFProtect`, and use it with `CSRFProtect(app)`.
The fontend of the System requests the backend API by adding 
```
headers: {
      "X-CSRFToken": csrf_token,
},
```
The `csrf_token` is from jinja2 template engine:
```
<script>
    var csrf_token = "{{ csrf_token() }}";
</script>
```
However, I don't know how to get the csrf_token with python script or RESTler to inject the headers in dictionary, is there any suggestion?

thank you!

Rex Lin

**Comment by robertpfeifer** [comment]
Hi @rreexxllii0310,

I'm not a contributor of the project but thought I'd share my thoughts anyway.

Please correct me if I'm wrong, but from what I can tell there is no way to make RESTler fetch access tokens for every request (i.e., run your script that would provide the same access token with different CSRF tokens).

Setting up a different build pipeline that disables the CSRF protection entirely via the [WTF_CSRF_ENABLED option](https://flask-wtf.readthedocs.io/en/0.15.x/config/) seems like an easy solution if you feel comfortable with making the assumption that the Flask-WTF library is safe.

Best regards,
Robert

**Comment by rreexxllii0310** [comment]
@rpbwp Thanks for replying!
