### ISSUE TITLE
Add configuration option to skip test of some operations (and their dependents)

### ISSUE THREAD

**Issue by mikekistler** [microsoft/restler-fuzzer#559]
It would be helpful to be able to tell Restler not to attempt to test certain operations, possibly because they require more extensive setup than can be accomplished by Restler.

An example is the "Update_PrivateEndpointConnections" operation in the Azure App Configuration service. App Configuration has no operation to create a "PrivateEndpointConnection" ... it must be created in the Networking service. But this can only be done for an existing "ConfigStore" and Restler dynamically creates all the ConfigStores it uses in a test run.  So there is no way to get a successful execution of "Update_PrivateEndpointConnections" and I'd like to be able to tell Restler to not bother trying.

**Comment by marina-p** [comment]
@mikekistler This has been merged in PR #614
