### ISSUE TITLE
Restler test not passing request param to dependent operation as defined in annotation

### ISSUE THREAD

**Issue by mikekistler** [microsoft/restler-fuzzer#562]
I used the following annotation to connect the DELETE for configStore to a GET for a deletedConfigStore:
```
    {
      "producer_endpoint": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppConfiguration/configurationStores/{configStoreName}",
      "producer_method": "DELETE",
      "consumer_endpoint": "/subscriptions/{subscriptionId}/providers/Microsoft.AppConfiguration/locations/{location}/deletedConfigurationStores/{configStoreName}",
      "consumer_method": "GET",
      "producer_resource_name": "configStoreName",
      "consumer_param": "configStoreName"
    },
```

But Restler used the value "null" as the configStoreName when calling the consuming GET operation:
```
"request_uri": "/subscriptions/774417ad-ece7-4ada-a4a2-c29ef9d57721/providers/Microsoft.AppConfiguration/locations/centralus/deletedConfigurationStores/null?api-version=2022-05-01",
```

I'll supply a zip file with result files separately.

**Comment by marina-p** [comment]
Hello @mikekistler,

Thank you for reporting this.  This is a bug in RESTler - there is an initialization missing (the 'writer' part in the statement below) that is causing the null value.   

>primitives.restler_static_string(_subscriptions__subscriptionId__resourceGroups__resourceGroupName__providers_Microsoft_AppConfiguration_configurationStores__configStoreName__put_name.reader(), quoted=False, **writer=_subscriptions__subscriptionId__resourceGroups__resourceGroupName__providers_Microsoft_AppConfiguration_configurationStores__configStoreName__delete_configStoreName_path.writer())**

```

Thanks,

Marina

**Comment by marina-p** [comment]
Hello @mikekistler,

I have pushed a fix to the mp/572 branch.  If you have a chance to try it, could you please confirm this fixes your issue?

Thanks,

Marina

**Comment by mikekistler** [comment]
Sadly this did not work. I’ve attached a zip of the directory

Mike

From: marina-p ***@***.***>
Date: Tuesday, July 5, 2022 at 11:23 PM
To: microsoft/restler-fuzzer ***@***.***>
Cc: Mike Kistler ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/restler-fuzzer] Restler test not passing request param to dependent operation as defined in annotation (Issue #562)

Hello @mikekistler<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikekistler&data=05%7C01%7Cmikekistler%40microsoft.com%7C97a4dc1d2c104a2f70c608da5f180958%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637926854085273746%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yvGYPi7f1P9HS%2F1P6CwAlLp3xAC%2BW23ZaZCXF%2B2P3bQ%3D&reserved=0>,

I have pushed a fix to the mp/572 branch. If you have a chance to try it, could you please confirm this fixes your issue?

Thanks,

Marina

**Comment by marina-p** [comment]
Hello @mikekistler,

Could you please re-try with the latest version of RESTler in main?  I deleted the mp/562 branch, since the code was merged.  

From main, using the config files in your zip, I get the correct grammar.py, which should have an additional variable below (this causes the DELETE to run before the GET of the deletedConfigStores).

``` 
__ordering____subscriptions__subscriptionId__resourceGroups__resourceGroupName__providers_Microsoft_AppConfiguration_configurationStores__configStoreName__providers_Microsoft_AppConfiguration_locations__location__deletedConfigurationStores__configStoreName_ = dependencies.DynamicVariable("__ordering____subscriptions__subscriptionId__resourceGroups__resourceGroupName__providers_Microsoft_AppConfiguration_configurationStores__configStoreName__providers_Microsoft_AppConfiguration_locations__location__deletedConfigurationStores__configStoreName_
```

Thanks,

Marina
