### ISSUE TITLE
[Feature Request] Include attempted operations in summary coverage message

### ISSUE THREAD

**Issue by mikekistler** [microsoft/restler-fuzzer#574]
### 💡 Idea

At the conclusion of a Restler run, a message is displayed:
```
Request coverage (successful / total): 17 / 24
```

It would be nice to indicate how many operations were attempted in this message, e.g.:
```
Request coverage (successful / attempted / total): 17 / 22 / 24
```

Where "attempted" means that a request was issued. Operations that were not attempted did not have a request issued because some dependent operation failed.

**Comment by marina-p** [comment]
Hello @MikeKistler,

How about printing the attempted number of requests on a separate line?  (To keep ```request coverage```  as a clear coverage metric of ```X/Y```.)

```
Request coverage (successful / total): 17 / 24
Attempted requests (executed / total): 21 / 24
```

Thanks,

Marina
