### ISSUE TITLE
Create a script to extract the configuration from RESTler logs

### ISSUE THREAD

**Issue by raych1** [microsoft/restler-fuzzer#585]
### Description

In the scenario of RESTler run in swagger PR pipeline, we need a script to extract the 'template configuration directory' from the RESTler logs. Then user can cook the config locally to improve on the coverage. Eventually check in the config to github spec repo to run RESTler with new config in pipeline.

**Comment by marina-p** [comment]
Hello @raych1,

The initial version of the script can be found in the #587 PR.  Can you please try this out and let me know your feedback?  

One note, right now in the PR there is a separate python script - eventually this could be integrated as a command into the RESTler driver, something like ```restler --generate_config <spec or directory with specs>```.  What do you think?

Thanks,

Marina

**Comment by ruowan** [comment]
Per my understanding, Current, the extract-config.py should be a part step of our swagger unified pipeline. To make sure I am fully understood, let me describe the whole process in swagger PR.


#### Pipeline process

Restler configuration will be stored in github spec repos. (dict.json, config.json, engine_setting.json, etc). 

1. Get related swagger file changes from PR 
2. Modify default restler config to include swggers file and update dict.json with preprepared variables. like(subscriptionId, resourceGroupName, location, etc). 
3. Check if there are already customized config stored in spec repo? If so, fetch config from spec repo and merge them into pipeline local config.
4. Restler compile.  restler compile --api_spec <spec path>
5. Extract configuration. python ./extract-config.py --compile_dir .\Compile
6. Restler run test mode
7. Publish restler output and report as artificact.
8. Publish configuration for further customized configurtion.

For improving local debug, there will be a doc about how to download pipeline restler configurations and reproduce locally.  

#### Questions

 Is restler config bind with resource provider or some specific api-version?   If restler config is insensitive with api-version, maybe the restlerConfig structure should be like this.

```
/restlerConfig
   /<resourceProvider>
      /config.json
      /dict.json
```

**Comment by marina-p** [comment]
Hi @ruowan,

The above pipeline process makes sense to me, except steps 4. and 5.  You should be able to instead run ```restler compile <config created in steps 2 and 3>```, then run ```test``` mode.  Let me know if I am missing something.

```restler --generate_config``` sounds good.

RE: is the RESTler config specific to an RP or specific ```api-version```?

The config will be specific to an RP (for example, there may be different dictionary custom payloads for different services, different throttling limits, etc.), and could include some ```api-version``` specific customizations as well.  For example, let's say v1 contains 5 endpoints, and v2 contains 10 endpoints - those additional 5 endpoints may require more custom payloads or annotations.  I don't know how common it would be to have conflicting values/data types for the latest and earlier version - maybe this is minimal given breaking changes are supposed to be minimized?  One approach could be to create a structure where there is a common config for all API versions, and then enable override configurations for a specific API version that can be put in a separate sub-folder?

**Comment by marina-p** [comment]
Hi @raych1 @ruowan,

I have updated the PR with the ```--generate_config``` option as discussed above.  Could you please try it out and let me know if it works as expected?  (The script shared earlier should no longer be needed with this option).

Usage:
PS > .\restler\restler.exe --generate_config <path to swagger file or directory> --config_dir_path <directory to create for the job configuration>

If the config_dir_path is not specified, a sub-directory in the cwd will be created.

Note: the content of the config files is not finalized yet (some of them need to be trimmed a bit).

Thanks,

Marina

**Comment by ruowan** [comment]
Thanks, I will try it.  Did you release a docker image with latest tag for this change? @marina-p one question: Does the option `--generate_config` support multi swagger file. Like `--generate_config a.json b.json`.

Currently, service team can customize these config which will be store in `spefication/<rp>/resource-manager/Microsoft.Contoso/preview/2020-06-01/restlerConfig` folder. 

```
 "dict.json",
  "engine_settings.json",
  "grammar.json",
  "config.json",
  "annotations.json",
```

There are two questions here:

1. is there any configuration missing here? Restler also generate grammar.py, I think for this file it's don't allow customize. 
2. Current customized folder name is `restlerConfig` which is specific for config? Do you think we may put any other restler file in this folder. Maybe a more common name. Like just `restler`. What do you think about these two names?

**Comment by marina-p** [comment]
Hi @ruowan,

>--generate_config will replace step4 and step5. So overall process is generate_config, update_generated_config_with_customized_config, restler test mode

This does not make sense to me given you are already modifying a "default RESTler config" in step 2.  My understanding was that the ```generate_config``` step would produce this "default RESTler config" in step 2.  I believe you can simply remove step 5., and add ```generate_config``` in step 2.

Re: your first two questions:
I will add the ability to specify a list of files.  The current version allows either a file or a directory.  Yes, you still need to compile separately after generating the config.


Re: testing changes - we need to figure out how you can test changes from a private branch that has not been released, via a different tag.  Perhaps support a variable somewhere that can take a "latest-experimental" tagged image?

Re: your two config questions:

1. Please do not allow customizing grammar.json.  This should be avoided because any changes to the spec will require manually merging the grammar.  I am not aware of any blockers that require modifying the grammar directly.  The rest of the config files are the most common settings and a good starting point for the initial release.

2. Either name seems fine to me.  Personally I'd prefer ```restler```  because it's shorter :)

Thanks,

Marina

**Comment by marina-p** [comment]
I've updated the branch to enable a list of files or directories.  Usage:

>restler\restler.exe --generate_config .\swaggers\swagger1.json .\swaggers\swagger2.json --output_dir .\temp

**Comment by marina-p** [comment]
Hi @ruowan, quick heads-up: I have merged the PR but after a bit more testing I need to update the parameters slightly, then I will push the new container version.

I am going to create two new tags:
```latest``` - build of the latest RESTler version tag.
```latest-main``` - build of the latest commit in main.

Thanks,

Marina

**Comment by marina-p** [comment]
Closing this issue since the `generate_config` feature has been fully implemented as in the discussion above.
