### ISSUE TITLE
The Extension function of Restler [for REST API Data Fuzzing]

### ISSUE THREAD

**Issue by painsAgains** [microsoft/restler-fuzzer#586]
### Description

  Recently，I read a paper " Intelligent REST API Data Fuzzing".It said there is a extension function called "body schema fuzzer" have implemented in RESTler.(and It appears that you are also the author of this paper）,Maybe because I was too careless， I can't find it in the project.
  So I wanna know is this extension available in this project ? And if it exists,could you tell me how to use it.
  Thanks a million

**Comment by marina-p** [comment]
Hello @painsAgains,

The code for this work is in the `payloadbody` checker, which is on by default for ```fuzz-lean``` and ```fuzz``` modes.  The checker itself is here: https://github.com/microsoft/restler-fuzzer/blob/main/restler/checkers/payload_body_checker.py

Thanks,

Marina

**Comment by painsAgains** [comment]
> 

Thanks, I will check it

**Comment by painsAgains** [comment]
> Hello @painsAgains,
> 
> The code for this work is in the `payloadbody` checker, which is on by default for `fuzz-lean` and `fuzz` modes. The checker itself is here: https://github.com/microsoft/restler-fuzzer/blob/main/restler/checkers/payload_body_checker.py. You can invoke it like any other checker, as described in [Checkers.md](https://github.com/microsoft/restler-fuzzer/blob/mp/directedvaluefuzz2/docs/user-guide/Checkers.md).
> 
> Thanks,
> 
> Marina

**Sorry to bother you again**,follow your prompts,I have try the payload_body_checker.But I still get some problem. When I have two request, such as **"/api/v1/componentstatuses"**  and **"/api/v1/componentstatuses/{name}"** ,the method of both requests is the **"GET" method**.And the value of "name" depends on the "/api/v1/componentstatuses" request returned by the "GET" method.And I found the checker can't work well. Then I found solution in Annotations.md,and I have try add annotations in my spec,just like this:
![image](https://user-images.githubusercontent.com/49607803/181208033-fbefcf4f-ebf1-48e7-ba20-2b7c270b2d4e.png)
and it does not work,the value of "name" is still "fuzzstring"
![image](https://user-images.githubusercontent.com/49607803/181208653-c8632297-a163-4cc5-a3ff-46d38242e54a.png)
The detail of  **"/api/v1/componentstatuses"** response is:
![image](https://user-images.githubusercontent.com/49607803/181208997-95236008-99f4-4b44-abf2-29a39c6ceb12.png)
And if the annotations way doesn't work, should I  use fuzz dictionary to fill in the values by default?(or change the grammar.py 

if you don't mind，I really hope you can help me.

Thanks a lot :)

**Comment by marina-p** [comment]
Hello @painsAgains,

You have an error in your annotation - the ```consumer_param``` needs to be ```name```.  Does this resolve the issue?

Thanks,

Marina

**Comment by painsAgains** [comment]
> Hello @painsAgains,
> 
> You have an error in your annotation - the `consumer_param` needs to be `name`. Does this resolve the issue?
> 
> Thanks,
> 
> Marina
Hello @marina-p 
Thanks，It works！
