### ISSUE TITLE
"IncludeOptionalParameters": true sends "readOnly" parameters resulting in invalid requests.

### ISSUE THREAD

**Issue by focus-nc** [microsoft/restler-fuzzer#593]
### Description

Parameters that are marked as "readOnly": true in the OpenAPI schema must not be sent in the request, per the spec.

However when the the compile option
"IncludeOptionalParameters": true
is set RESTler includes every single property in the request despite some of them being marked as "readOnly"

### Steps to reproduce

Using the attached schema, the first request generated is a POST to "/quotes" to create a record with an "id" to be used in subequent requests.

The Body is this:
{
    "id":"a4e80a35-f2c4-486b-b706-58298c0aa4d7",
    "dummy":"fuzzstring"
}

But "id" is "readOnly"
          "id": {
            "type": "string",
            "description": "Quote ID.",
            "format": "uuid",
            "nullable": true,
            "readOnly": true
          },

[swagger-bug.zip](https://github.com/microsoft/restler-fuzzer/files/9221413/swagger-bug.zip)

### Expected results

The rendered Body should only include valid properties:
{
    "dummy":"fuzzstring"
}

### Actual results

The rendered Body for the Post is:
{
    "id":"a4e80a35-f2c4-486b-b706-58298c0aa4d7",
    "dummy":"fuzzstring"
}

Which is invalid per the schema, and hence the request fails.

**Comment by marina-p** [comment]
This has been fixed with #639
