### ISSUE TITLE
dotnet error when running quick start

### ISSUE THREAD

**Issue by aharpervc** [microsoft/restler-fuzzer#60]
The quick start guide says I need an OpenAPI spec (which I have), and then shows a python command (not explicitly stated, but I have python). Running that command gives me this error:

```sh
$ python restler-quick-start.py --apiSpec ../openapi.yaml --restler_drop_dir .drop/
No executable found matching command "dotnet-/mnt/c/Users/aharper/workspace/api-v3/.restler/.drop/restler/Restler.dll"
```

This seems to imply there are additional steps to get going from scratch not described in the quick start guide. From looking at the readme, there is a "build" section which references dotnet, so I'm guessing that the build instructions are also a prerequisite not mentioned in the quick start. Is that right? Are there any other prerequisite steps to get started?

I recommend reviewing that doc from the perspective of a new user who isn't familiar with your project and has no additional context, and trying to follow your own directions and seeing if it works.

**Comment by aharpervc** [comment]
After following the build instructions and running the quick start script again, I get this error:

```sh
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      2.1.14 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      5.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

The readme says that 3.1 or greater is supported, but I wonder if that is accurate since I'm using 5.0 and it's not working?

**Comment by marina-p** [comment]
@aharpervc This is a bug in the README.   At the moment, you need to have dotnet 3.1.0 installed.  Could you please try that, and let us know if this resolves the error?

Re: build instructions, that makes sense, we will add that as a pre-requisite to the quick start (feel free to send PR if you have time).
