### ISSUE TITLE
[Feature Request] Support for path parameters being embedded into the path directly

### ISSUE THREAD

**Issue by evanweissms** [microsoft/restler-fuzzer#613]
### 💡 Idea

For example, a format like api/v{verison}/ is not supported. It would be great if in-line parameters could be supported. I'd treat this as low-priority since it probably is a rarer case and falls outside most swagger conventions.

**Comment by marina-p** [comment]
Hello @evanweissms,

This has been merged with #758.  Closing the issue.

Thanks,

Marina
