### ISSUE TITLE
[Feature Request] "maximum N resources alive at once" to support quota

### ISSUE THREAD

**Issue by ruowan** [microsoft/restler-fuzzer#615]
### 💡 Idea

By default, Restler executes an independent set of API calls for each test. This is to ensure that each test result is independent.  And restler will create a lot of resource in one run.

Due to there are limitations in quota, so restler should support option to control the number of created resources.

**Comment by marina-p** [comment]
Implemented #618 to clean up resources after every sequence.

Note: #618 is only applicable in 'Test' mode without checkers - checkers may create additional resources which can exceed quota.

Changing the title and closing the issue per offline discussion.
