### ISSUE TITLE
RESTler dropped `Content-type` header from request resulting in 415 response

### ISSUE THREAD

**Issue by mikekistler** [microsoft/restler-fuzzer#626]
### Description

Running RESTler on the Azure Keyvault (resource-manager) service. RESTler issued a request to create a keyvault but failed to include the Content-type header in the request, so the service failed the request with a 415 status code.

I've attached the RESTler network.testing file.
- The log for the failing request starts at line 434.
- Lines 472-473 seem to show that RESTler knows it should add `Content-type: application/json`
- Line 531 shows the full request and this does not contain a `Content-type` header

[network.testing.139800614484792.1.txt](https://github.com/microsoft/restler-fuzzer/files/9549454/network.testing.139800614484792.1.txt)

### Steps to reproduce

I have not attempted to reproduce ... hoping that the log file will be sufficient to debug.

### Expected results

RESTler should include Content-type whenever it sends a body.

### Environment details

Python: 3.10.5

**Comment by marina-p** [comment]
Hello @mikekistler,

I have reproduced this problem.   This should be fixed soon.

Thanks,

Marina
