### ISSUE TITLE
RESTler must URL-encode example query parameter values

### ISSUE THREAD

**Issue by mikekistler** [microsoft/restler-fuzzer#627]
### Description

The "Vaults_List" operation in Azure Keyvault defines a [`$filter` query parameter](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/keyvault.json#L633) and the [example value for `$filter`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/examples/listVault.json#L3) contains characters (specifically spaces) that must be URL encoded:
```
    "$filter": "resourceType eq 'Microsoft.KeyVault/vaults'",
```

But it appears that RESTler does not encode this value:
```
2022-09-01 06:34:39.824: Sending: "GET /subscriptions/db5eb68e-73e2-4fa8-b18a-46cd1be4cce5/resources?$filter=resourceType eq 'Microsoft.KeyVault/vaults'&$top=1&api-version=2015-11-01 HTTP/1.1\r\nAccept: application/json\r\nHost: test-proxy\r\nx-recording-id: 2b9a2e3b-e9d4-4fab-9fe6-1652cf0dbb69\r\nx-recording-mode: record\r\nx-recording-upstream-base-uri: https://management.azure.com\r\n_OMITTED_AUTH_TOKEN_\r\nContent-Length: 0\r\nUser-Agent: restler/9.0.1\r\n\r\n"
```
 

### Steps to reproduce

Run RESTler on Azure KeyVault (mgmt plane).

### Expected results

Example values of query params are correctly URL-encoded.

### Actual results

Currently example values of query params are not being URL-encoded.

### Environment details

Python: 3.10.5

**Comment by Oleggg2000** [comment]
Hi, i'm using RESTler and i woundering if there's an switch for disabling URL-encoding of query parameter. My testing server feels bad about it. Moreover when i looked at tcp dump i saw that url params looks like still url-encoded. 
Actual result:
![image](https://user-images.githubusercontent.com/62327850/228426686-fde47d3c-7660-46e0-9537-2804828d5bac.png)
Expected result:
![image](https://user-images.githubusercontent.com/62327850/228426981-6e8c6d20-2487-4b17-ab26-7da5f29c2253.png)

**Comment by Oleggg2000** [comment]
Probably there's an issue with parsing API specification. On your right my OpenAPI specification and left RESTler generized file restler_grammar_grammar_27328.py from ..\restler_working_dir\Test\RestlerResults\experiment27328
![image](https://user-images.githubusercontent.com/62327850/228440338-97c31ef7-dbd4-480d-a201-519a092f00e3.png)
