### ISSUE TITLE
[Feature Request] Reslter support polling delete resource operation status until it finish

### ISSUE THREAD

**Issue by ruowan** [microsoft/restler-fuzzer#653]
### 💡 Idea

For azure resource, the deletion is long running operation. And it has fixed pattern to pull the deletion operation status. To avoid create too many resources at the same time, the next `create-delete` test should wait until the previous delete finish. 
restler should polling status for delete operation until the operation finish.

**Comment by marina-p** [comment]
This has been implemented in #660 and #618
