### ISSUE TITLE
Where is the source code path for constructing the request sequence

### ISSUE THREAD

**Issue by painsAgains** [microsoft/restler-fuzzer#668]
### Description

Does anyone know where the source code path to construct the request sequence is?Just like the `EXTEND` function and `RENDER` function in Fig 4 : Main Algorithm used in REST-ler  in the paper `REST-ler: Automatic Intelligent REST API Fuzzing`
![image](https://user-images.githubusercontent.com/49607803/204769061-7efc755a-0fdb-4c6d-8be2-c8cb6875ebcc.png)

Is that in the path `restler-fuzzer/restler/engine/core/sequences.py`?

Hope someone can help me,
Thanks

**Comment by marina-p** [comment]
Hello @painsAgains,

This code is in ```driver.py``` in the function ```generate_sequences```.

It has been extended a bit since the original paper but you can see the basic structure on lines 666-700, for example:

```python
seq_collection, extended_requests = extend(seq_collection, fuzzing_requests, global_lock)
# ...
seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock,
                                            garbage_collector)
```


Thanks,

Marina

**Comment by painsAgains** [comment]
> Hello @painsAgains,
> 
> This code is in `driver.py` in the function `generate_sequences`.
> 
> It has been extended a bit since the original paper but you can see the basic structure on lines 666-700, for example:
> 
> ```python
> seq_collection, extended_requests = extend(seq_collection, fuzzing_requests, global_lock)
> # ...
> seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock,
>                                             garbage_collector)
> ```
> 
> Thanks,
> 
> Marina

Thanks! I will check it

**Comment by painsAgains** [comment]
> Hello @painsAgains,
> 
> This code is in `driver.py` in the function `generate_sequences`.
> 
> It has been extended a bit since the original paper but you can see the basic structure on lines 666-700, for example:
> 
> ```python
> seq_collection, extended_requests = extend(seq_collection, fuzzing_requests, global_lock)
> # ...
> seq_collection = render(seq_collection, fuzzing_pool, checkers, generation, global_lock,
>                                             garbage_collector)
> ```
> 
> Thanks,
> 
> Marina

Sorry to bother you again,I have made some changes to the driver.py file, but when I use the following command
```dotnet "../restler_bin/restler/Restler.dll"  fuzz --grammar_file "./Compile/grammar.py" --dictionary_file "./Compile/dict.json" --settings  "./Compile/engine_settings.json"```
I can't observe the changes I made， I want to know does the command as the above could automatically call the driver.py file? And what is the call chain of driver.py？If I want to test my changes what should I do?

**Comment by painsAgains** [comment]
> 

I have tried rebuilding the restler use build-restler.py
