### ISSUE TITLE
Payload body checker can't handle bodies that don't start with '{'

### ISSUE THREAD

**Issue by rifiles** [microsoft/restler-fuzzer#67]
Payload body checker can't handle bodies that don't start with '{'.

For instance, if a body is a list, which is still valid json, it will fail.

It fails first because it can't find the body (doesn't start with '{').
If the above is handled for '[' it will behave incorrectly because it assumes the body will always start with a key value pair, so the replacement bodies are created like this: "": [ "..." ] instead of simply [ "..." ]

**Comment by marina-p** [comment]
@rifiles Is the missing functionality just to handle json arrays?

**Comment by rifiles** [comment]
> @rifiles Is the missing functionality just to handle json array

Pretty much, yes.
