### ISSUE TITLE
Very low API coverage with Azure Storage 

### ISSUE THREAD

**Issue by anna-mazhar** [microsoft/restler-fuzzer#677]
### Description

**Problem**
I configured RESTler for Azure Storage and found it to have a very low API coverage i.e., 2/69 in the Test mode. 

**Description**
To test Azure Blob Storage, I ran RESTler on its [data-plane swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/storage/data-plane/Microsoft.BlobStorage/preview/2021-12-02/blob.json) specifications and found the coverage to be 2/69. 
Experiments were run on Windows 10 pro, Microsoft Azure VM with 16 GB physical memory.

The reasons for failed requests are the following:
1. An HTTP header that is mandatory for this request is not specified (31 requests -- most frequent).
2. The specified container does not exist (15 requests).
3. The value for one of the HTTP headers is not in the correct format (6 requests).
4. A query parameter that's mandatory for this request is not specified (2 requests).
5. Value for one of the query parameters specified in the request URI is invalid (4 requests).
6. HTTP Error 400. The request has an invalid header name (2 requests).

To address issues 1 and 4, changes to swagger specs are required. I use the latest available spec (linked) but from the results, it seems like the spec is not consistent with the current Azure Storage service. For issue 2, RESTler being unable to infer dependencies seems to be the cause. For other issues, it seems like custom values need to be set.

**Question**
I believe that the RESTler team was able to get a good coverage with Azure Storage (control-plane and data-plane). Could you share if you had to make plenty of changes to the swagger specs and the dictionary in order to increase the coverage? Or am I likely missing something in my setup?
<br/>

Also, note that when tested with [control-plane swagger](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/storage/resource-manager/Microsoft.Storage/stable/2022-09-01/blob.json) specifications of blob, the coverage was 13/17 (approximately 80% -- which is decent).

**Comment by anna-mazhar** [comment]
Ignore the first reason for failed requests. These reasons were reported from speccov.json which is affected by a possible bug reported here: https://github.com/microsoft/restler-fuzzer/issues/680

**Comment by marina-p** [comment]
Hello @anna-mazhar,

The RESTler configuration for Azure Storage requires many annotations, because of the use of the Microsoft-specific ```x-ms-paths``` which prevents RESTler from inferring dependencies.  Could you please send me an e-mail (you can find it in the research papers linked in the README) for more details?  

Thanks,

Marina
