### ISSUE TITLE
ln: file exists when building Docker image

### ISSUE THREAD

**Issue by mastercoms** [microsoft/restler-fuzzer#687]
### Description

```
 => ERROR [target 3/5] RUN ln -s /usr/bin/python3 /usr/bin/python               0.2s
------
 > [target 3/5] RUN ln -s /usr/bin/python3 /usr/bin/python:
#7 0.211 ln: /usr/bin/python: File exists
------
executor failed running [/bin/sh -c ln -s /usr/bin/python3 /usr/bin/python]: exit code: 1
```

### Steps to reproduce

Run `docker build -t restler .`

**Comment by hidingturtle** [comment]
I also have this issue and I found a workaround by removing both lines in the Dockerfile containing the `ln` command. You could also just comment them out with a `#` at the beginning of their lines.
