### ISSUE TITLE
Add startup wait for RESTler

### ISSUE THREAD

**Issue by stishkin** [microsoft/restler-fuzzer#69]
When starting a service under test and RESTler at the same time; RESTler fails with "connection refused" since service under test is still starting up.

Suggestion: Add a startup wait parameter to RESTler. Thus allowing RESTler to ignore refused connection until start up wait timeout expired

**Comment by marina-p** [comment]
@stishkin I don't think this makes sense as a tool feature in RESTler.  This coordination should be done by the agent or framework that's responsible for starting the service.
