### ISSUE TITLE
"build-restler.py" fails on windows machine on line 127, i.e. when subprocess.run is executed

### ISSUE THREAD

**Issue by killswitch-2434** [microsoft/restler-fuzzer#707]
### Description

In build-restler.py script, when the following function is executed:
 `completed_process = subprocess.run(f'{dirs.python_path} -m compileall -q {dirs.engine_build_dir}', shell=True, capture_output=True, check=True)
`
the build might fail if there is a space in the python executable full path.

### Steps to reproduce

The build might fail if the "python_path" var has spaces in the python path. For example, my python executable was in "Program Files" dir, so it was failing due to the space in dir name and giving the following error:
```
Build failed!
Exit code: 1
b"'C:\\Program' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
Removing engine compilation build directory...
```

### Solution:

I modified the script as follows to make it work:
`completed_process = subprocess.run([str(dirs.python_path), '-m', 'compileall', '-q', str(dirs.engine_build_dir)], shell=True, capture_output=True, check=True)`

### Environment details

Windows

**Comment by killswitch-2434** [comment]
> I'm running into this as well.

can you share the error output of the script? If its the same error, can you try the solution in the post.

**Comment by marina-p** [comment]
Hello @killswitch-2434,

Thank you for reporting this.  The fix will be merged shortly.

Thanks,

Marina
