### ISSUE TITLE
Enum support for path values

### ISSUE THREAD

**Issue by hidingturtle** [microsoft/restler-fuzzer#714]
### Description

Hello,

does RESTler support Enums in the path of a request? (e.g. the path is `/{test}` and `{test}` is declared as an enum of strings).

I ask because it seems like it does not support it. The enum gets sent as the default object that is found in the dictionary and trying to change it manually in the `grammar.json` also gives me the message `Compile failed`.

**Comment by marina-p** [comment]
Hello @hidingturtle,

Yes, it is supported.  Can you please share a snippet of your specification with the parameter definition?  There may be a bug/lack of support in compiling the enum as it appears in your spec.  

If it works, you should see the following in the grammar.py for the path parameter:
```    primitives.restler_fuzzable_group("", ['asc','desc']  ,quoted=False),```

Thanks,

Marina

**Comment by hidingturtle** [comment]
Hi @marina-p ,

The whole OpenAPI spec can be found [here](https://github.com/jdegre/5GC_APIs/blob/Rel-16/TS29503_Nudm_UEAU.yaml).

The problematic path parameter is `hssAuthType`, which is defined as follows:

```
...
/{supi}/hss-security-information/{hssAuthType}/generate-av:
    post:
      summary: Generate authentication data for the UE in EPS or IMS domain
      operationId: GenerateAv
      tags:
        - Generate HSS Authentication Vectors
      parameters:
        - name: supi
          in: path
          description: SUPI of the user
          required: true
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
        - name: hssAuthType
          in: path
          description: Type of AV requested by HSS
          required: true
          schema:
            $ref: '#/components/schemas/HssAuthTypeInUri'`
...
HssAuthTypeInUri:
      anyOf:
        - type: string
          enum:
          - eps-aka
          - eap-aka
          - eap-aka-prime
          - ims-aka
          - gba-aka
        - type: string
...
```
While the `hssAuthType` parameter in the request bodies work (but they also reference something else), the one for the path results in only being sent as `{ \"fuzz\": false }`, which can be seen in `grammar.json`:

```
...
"id": {
        "endpoint": "/{supi}/hss-security-information/{hssAuthType}/generate-av",
        "method": "Post"
      },
      "method": "Post",
      "basePath": "/nudm-ueau/v1",
      "path": [
        {
          "DynamicObject": {
            "primitiveType": "String",
            "variableName": "__supiOrSuci__security_information_generate_auth_data_post_supi",
            "isWriter": false
          }
        },
        {
          "Constant": [
            "String",
            "hss-security-information"
          ]
        },
        {
          "Fuzzable": {                                            <-- this is supposed to be hssAuthType
            "primitiveType": "Object",
            "defaultValue": "{ \"fuzz\": false }"
          }
        },
        {
          "Constant": [
            "String",
            "generate-av"
          ]
        }
      ],
...
```

Could you tell me how an enum in the grammar.json is supposed to look like? I tried to add it like the enums from the request bodies but then it does not work.

**Comment by marina-p** [comment]
Hello @hidingturtle,

The bug fix that will fix your repro should be merged shortly.

However, note that RESTler does not fully support 'AnyOf', it currently picks the first type in the list.  In case you need to work around this and cannot modify the spec, this is what the grammar looks like for the enum in path:

```
    primitives.restler_static_string("hss-security-information"),
    primitives.restler_static_string("/"),
    primitives.restler_fuzzable_group("hssAuthType", ['eps-aka','eap-aka','eap-aka-prime','ims-aka','gba-aka']  ,quoted=False),
    primitives.restler_static_string("/"),
```

```
        {
          "Fuzzable": {
            "primitiveType": {
              "Enum": [
                "hssAuthType",
                "String",
                [
                  "eps-aka",
                  "eap-aka",
                  "eap-aka-prime",
                  "ims-aka",
                  "gba-aka"
                ],
                null
              ]
            },
            "defaultValue": "eps-aka"
          }
        },

```


Thanks,

Marina
