### ISSUE TITLE
Print values while restler is running

### ISSUE THREAD

**Issue by alaendro** [microsoft/restler-fuzzer#720]
### Description

While Restler is running I wanted to check some values through the print function in python but it wasn't possibile, how could I do it? I tryied writing in a txt file but it doesn't work out.

**Comment by marina-p** [comment]
Hello @alaendro,

For your scenario, I recommend writing to the existing network logs with some prefix that you can then use to easily search for to filter out your output.

Also, there was a python error in the print statement above which caused the engine to crash - the call stack is printed in the EngineStdOut.txt file in the task directory.

Here is a line that worked for me:

```
                RAW_LOGGING("DEBUG: prev_response json " + prev_response.json_body + " body " + prev_response.body) #print value returned
```

output on demo_server:
```
2023-03-29 18:28:36.992: prev_response json {"id":22,"body":"my first blog post"} body {"id":22,"body":"my first blog post"}
```

Thanks,

Marina

**Comment by alaendro** [comment]
I followed your advice but I still not get the output on the EngineStdOut.txt file, there's some option I need to use before start a fuzzing or a test? This are the commands that I'm using

`restler_bin/restler/Restler compile --api_spec test_8_stdout/swagger.json `

`restler_bin/restler/Restler test --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings Compile/engine_settings.json --no_ssl`

`restler_bin/restler/Restler fuzz-lean --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings Compile/engine_settings.json --no_ssl`

`restler_bin/restler/Restler fuzz --grammar_file Compile/grammar.py --dictionary_file Compile/dict.json --settings Compile/engine_settings.json --no_ssl --time_budget 0.03`

If can be useful, I have imported the function from here 
`from utils.logger import NetworkLog, raw_network_logging as RAW_LOGGING`
and I also tried with the _RAW_LOGGING imported from here
`from engine.core.request_utilities import _RAW_LOGGING`
but nothing seems to work correctly

**Comment by marina-p** [comment]
Hello @alaendro,

The output from `RAW_LOGGING` will be present in the `network.testing.*.txt` file.  It will be interleaved with the other output from RESTler using this function, but if you include a prefix (such as 'DEBUG'), you can easily filter these and output to a different file.  The advantage of including this in the network log is that you can see when your output was printed relative to the rest of the execution.

Thanks,

Marina
