### ISSUE TITLE
incorrect example values in URL

### ISSUE THREAD

**Issue by Oleggg2000** [microsoft/restler-fuzzer#724]
### Description

Hi, i'm using RESTler and i wondering if there's an switch for disabling URL-encoding of query parameter. My testing server feels bad about it. Moreover when i looked at tcp dump i saw that url params looks like still url-encoded.
Actual result:
![image](https://user-images.githubusercontent.com/62327850/229469043-de71dfb6-df06-4fc5-9718-c3c50096cd22.png)
Expected result:

**Comment by Oleggg2000** [comment]
Expected result:
![image](https://user-images.githubusercontent.com/62327850/229469176-7b7cae0d-c234-4b74-bef0-3669625c72cf.png)
Probably there's an issue with parsing API specification. On your right my OpenAPI specification and left RESTler generated file restler_grammar_grammar_27328.py from ..\restler_working_dir\Test\RestlerResults\experiment27328
![image](https://user-images.githubusercontent.com/62327850/229469303-c775c981-b24f-4c8f-84bf-4046d9d03b72.png)

**Comment by Oleggg2000** [comment]
I'm so sorry, but i still have an question about switch existance for disabling URL-encoding of query parameter. Is there anything like that?

**Comment by marina-p** [comment]
Hello @Oleggg2000,

There currently isn't a way to disable URL encoding for query params.  Could you please file a new issue for this feature?

If you want to disable it by modifying the code directly, you could do this relatively easily by modifying the offsets on line 1215 in `requests.py`:

```
                url_encode_start, _ = req.get_path_and_query_start_end()
                url_encode_end, _ = req.get_query_start_end()
                url_encode_end -= 1
```

Thanks,

Marina
