### ISSUE TITLE
Is RESTler can handle python scripts as token generation source? 

### ISSUE THREAD

**Issue by onmywaytoheaven** [microsoft/restler-fuzzer#75]
Hi!
Is RESTler can handle python scripts as token generation source? 
Its looks like it is, but i cant get it work.

What i did:

1. Create python script which returns:
`return ("{'appname':{}} + "\n" + "<header-tag-name>: <token>")`
2. Make it executable
3. Run script from command line with its absolute path to enshure that it returns what expected
4. Provide abs. path to script via `--token_refresh_command "/absolute/path/script.py"` and set `--token_refresh_interval 10` and run restler

What i expect:
No 401 errors in Test/logs and increasing coverage (almost all endpoints require auth)

What i have:
0 coverage, only 401 errors

Could you please help and provide some details how to deal with this problem?

Thank you in advance!

**Comment by marina-p** [comment]
Hello,

The full command line is required (same as what you'd run from a command prompt).  Can you try this modified command line (make sure python is on the path, or full path to python)?

```
python /absolute/path/script.py
```

Also, the script needs to print the token info to the console.

**Comment by onmywaytoheaven** [comment]
I tried to run restler with full path to python `--token_refresh_command "/bin/python /absolute/path/script.py"`, but it still dont work
Also i tried to:
1. Change `return(...)` to `print(...)` and to `stdout.write(...)`
2. Run `execute_token_refresh_cmd("/bin/python /absolute/path/script.py")` from `engine.core.request_utilities` and it successfully assign `"<header-tag-name>: <token>"` to `latest_token_value`

My script below
```
#!/usr/bin/env python

import sys
import json
from requests import post

URL = "..."
DATA = {...}

def main(argv=None):
    r = post(URL, json=DATA)
    j = json.loads(r.content.decode())
    sys.stdout.write("{'localhost':{}}\n")
    sys.stdout.write("<token-tag-name>: {0}".format(j.get("<token-tag-name>")))
if __name__ == "__main__":
    sys.exit(main())
```

**Comment by onmywaytoheaven** [comment]
Well, it was my mistake. Its was not clear for me, that i need to set `"UseRefreshableToken": true` in compile config
Thank you

**Comment by PatGod** [comment]
@onmywaytoheaven Thanks for letting us know what the problem was and how you were able to resolve this issue! (Yes, RESTler has many config options...)
