### ISSUE TITLE
Issue specifying the host address

### ISSUE THREAD

**Issue by hydroculator** [microsoft/restler-fuzzer#762]
### Description

I'm having difficulty figuring out exactly how and where to specify the host address.

In these examples, the URL has been replaced with <address> to protect the innocent. "http://" not included. If I used it, I specify it below. 

If I put this in the command line:
`--host <address name> --target_port 443`
Then I get this:
"400 Bad Request The plain HTTP request was sent to HTTPS port"

If I do this:
`--host https://<address name> --target_port 443`
I get this:
"Unknown error: 'Exception Creating Socket: [Errno -2] Name or service not known'"

If I do neither, and specify those in the settings.json file instead, I get: 
```
    "target_ip": "<address name>",
    "target_port": 443,
```
"400 Bad Request The plain HTTP request was sent to HTTPS port"

and with this:
```
    "target_ip": "https://<address name>",
    "target_port": 443,
```
I get: "Unknown error: 'Exception Creating Socket: [Errno -2] Name or service not known'"

I've swapped out <address name> with the IP address and get the same thing...

Any suggestions how to get this to work?
Thanks

**Comment by hydroculator** [comment]
I was using the no_ssl option to prevent a different error. If I removed that and went with disable_cert_validation instead, the connection is made.

**Comment by IrfanSyed-PSC** [comment]
I am facing the same problem, how did you solve the problem ? Did you use https in the host or not ? and I do not see "disable_cert_validation" anywhere in the options. How do I provide that ?
