### ISSUE TITLE
Create a pipeline to build a docker image

### ISSUE THREAD

**Issue by mgreisen** [microsoft/restler-fuzzer#78]
The project https://github.com/microsoft/rest-api-fuz-testing needs a docker image to build on-top of. Create an image built on alpine linux. This should be build pulling from a tag or commit and saved into a test azure repository or pushed public when passing all testing stages.

**Comment by marina-p** [comment]
@mgreisen publish-restler.yml will be run within the RAFT project, is that correct?

**Comment by marina-p** [comment]
@mgreisen It's unclear from the description what change is needed to the existing RESTler CI pipeline.

**Comment by mgreisen** [comment]
@marina-p 
The publish-restler.yml will be run as a pipeline in the ADO restler project. It will not be run as part of the RAFT project. 
The existing pipeline changes only include an extra uncompressed pipeline artifact drop.

**Comment by marina-p** [comment]
Closing since the PR has been merged.
