### ISSUE TITLE
Spec coverage file speccov-min.json not found.

### ISSUE THREAD

**Issue by jebuiz** [microsoft/restler-fuzzer#781]
### Description

I am trying to run RESTler through GitHub Actions. However, I keep getting this message: Spec coverage file speccov-min.json not found. RESTler still runs about it is giving 0/10 coverage. It works fine locally, but appears to not work on GitHub Actions. Any advice?

**Comment by marina-p** [comment]
Hello @jebuiz,

Do you get any output files after RESTler finishes in the GitHub actions?  If yes, what is in the EngineStdOut.txt and EngineStdErr.txt?  Is there a RestlerResults\experiment___\logs\'network.testing.*.txt' log in the task directory, and if yes does that same directory contain any 'speccov' files?

Thanks,

Marina

**Comment by jebuiz** [comment]
This ticket can be resolved. The path to my access token was incorrect.
