### ISSUE TITLE
Provide authentication for the requests

### ISSUE THREAD

**Issue by Hrushikar** [microsoft/restler-fuzzer#801]
### Description

Hi,

I am trying to setup token-based authentication to be used by RESTler to authenticate the requests, but I am not sure how to provide the token and what exactly to be mentioned in the format given in [Authentication.md](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/Authentication.md). The requests I am trying to fuzz use a bearer token (JWT) for authentication.

I have searched for if there were any previous cases of users with the same query, but couldn't find any.
Can anyone help/guide me to set it up?

**Comment by Oleggg2000** [comment]
- You need to specify token.txt, module of run script. In my case file:
`{u'user': {u'name': 'MY_TOKEN'}, u'oper': {u'name': 'MY_TOKEN2'}}
ACCESS-TOKEN: ey
ACCESS-TOKEN: yAic3V`

- Then add this structure to engine_settings.json
`{
"authentication": {
    "token": {
      "location": "D:\\token.txt", 
      "token_refresh_interval":  300
    }
}`

- Don't forget to add engine_settings path to compiling config.json
`{
"EngineSettingsFilePath": "D:\\engine_settings.json",
}`

- Run `Restler.exe compile config.json` and u'll see line like that in your grammar.py _primitives.restler_refreshable_authentication_token("authentication_token_tag")_

**Comment by Hrushikar** [comment]
Thanks @Oleggg2000. That was helpful.

I have one more issue pertaining to this, which is to provide a refresh command/module for the RESTler to refresh the auth token and use the new one.

How to provide the token initially for the tool to even begin the scan along with the refresh module for it to refresh and use the new token later on?
