### ISSUE TITLE
Is the default for fuzzing mode bfs or bfs-fast?

### ISSUE THREAD

**Issue by Marcondiro** [microsoft/restler-fuzzer#834]
### Description

Hello,
According to the [documentation for the settings file](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/SettingsFile.md#fuzzing_mode-str-default-bfs) the default fuzzing mode should be BFS. Running the fuzzer without explicitly choosing a fuzzing mode, I get this in the `logs/main.txt`: `Setting fuzzing schemes: bfs-fast`.
I'm wondering which one is the actual default. :)
Thanks!

**Comment by marina-p** [comment]
Hello @Marcondiro,

Currently, the default is `bfs-fast`, but this will soon be changed (see discussion in issue #823 - we will fix the documentation as part of that update).  

Thanks,

Marina

**Comment by Marcondiro** [comment]
Perfect, thanks!
