### ISSUE TITLE
remove the compiler setting 'UseRefreshableToken'

### ISSUE THREAD

**Issue by marina-p** [microsoft/restler-fuzzer#87]
The fact that this is a setting in the compiler causes the following two usability issues:

1) The compiled grammar from the quick start cannot be used, just adding authentication (user must find this in the setting, and set it in addition to setting the --token_refresh_command)

2) The grammar can't be easily used for parity testing with vs. without authentication.

## Proposal:

- Always generate the refreshable authentication token element in the grammar.
- If the ``--token_refresh_command`` is set, then invoke it and substitute the token
- If there is no token refresh command, the grammar element refreshable_authentication_token 'is ignored.

Always

**Comment by marina-p** [comment]
This addresses the ux issue that led to question #75.

**Comment by PatGod** [comment]
sounds like a great idea! (keep it simple, we have a lot of options already, the fewer the better... ;-)

**Comment by PatGod** [comment]
PS: for this change to be backward-compatible, please let's not crash when this option is still specified (in old jobs like from the author of #75), but simply ignore this option (no-op) after this change.

**Comment by marina-p** [comment]
For the backwards compat, the option data type should be changed to an option type, and the default should be set to:

```UseRefreshableToken = Some true```

Let's discuss how to deprecate these - e.g. we could do so in the next major version update.
