### ISSUE TITLE
Specifying unique parameters

### ISSUE THREAD

**Issue by JoshuaEN** [microsoft/restler-fuzzer#88]
Hello,

Is it possible to specify via annotations or a fuzzing dictionary what parameters to a request need to be unique?

#### Use cases
`POST` on `/resources` to create where the server honors the user-provided unique identifier in the request body. [Example repository/branch](https://github.com/JoshuaEN/restler-fuzzer-testing/tree/problem/uniqueness-required) ([RESTler-fuzzer output](https://github.com/JoshuaEN/restler-fuzzer-testing/tree/problem/uniqueness-required/Server/restler-fuzzer/results)).
_Current behavior: A fuzzable value is provided, causing 409 errors when RESTler-fuzzer attempts to create several of the same resource._

`PUT` on `/resources/{resourceId}` to create where the server expects the `resourceId` in the URL to match an identifier param in the request body. [Example repository/branch](https://github.com/JoshuaEN/restler-fuzzer-testing/tree/problem/matching-uniqueness-required) ([RESTler-fuzzer output](https://github.com/JoshuaEN/restler-fuzzer-testing/tree/problem/matching-uniqueness-required/Server/restler-fuzzer/results)).
_Current behavior: A unique ID is provided for the resourceId in the URL, but a fuzzable value is provided in the body, causing 400 errors._

Note: These are cases from an existing real-world (closed-source/non-public) REST API.

#### Desired Functionality
Specifically, what I'm looking for is (in a maintainable/declarative manner):
1. A way to specify which parameter names for a request (or globally) should be unique
1. And for those unique parameters, which ones within a request should match (have the same unique value)

From my limited testing, this appears to be possible and work as desired when modifying the grammar.py directly to use `primitives.restler_custom_payload_uuid4_suffix` in place of `restler_fuzzable_string`, including that passing the same suffix in several places in the request sends the same unique value.

However, modifying the grammar (json or py) seems hard to maintain.

Thank you for your time,
Joshua

----

#### What I've tried
1. Adding the param name to the fuzzing dictionary under `restler_custom_payload`
1. Adding the param name to the fuzzing dictionary under `restler_custom_payload_uuid4_suffix`
1. Adding inline swagger annotations specifying the `producer_resource_name` as:
     1. `"restler_fuzzable_uuid4"`
     1. `"restler_custom_payload_uuid_suffix__id"` with a corresponding entry in the fuzzing dictionary

I did note the docs mention unique ids in the [Fuzzing Dictionary](https://github.com/microsoft/restler-fuzzer/blob/main/docs/user-guide/FuzzingDictionary.md) guide, however this appears to be in the context of specifying a suffix to a unique ID rather than specifying what parameters should be unique.

**Comment by rifiles** [comment]
Hi Joshua,

To answer your first question about unique resources, I believe this can be solved using the create-once feature. This feature allows you to specify an endpoint in the settings file whose resource(s) will only be created once at the start of the fuzzing run and then deleted at the end of the run.

To do this, include the endpoint in the "per_resource_settings" dict in the settings file and add "create_once": 1 as one of that endpoint's options, like so:

"per_resource_settings": {
    "/your/endpoint/resourcetobecreatedonce" : {
        "create_once": 1
    }
}

If the producer-consumer dependencies for this request are correct in the grammar, the requests that consume the singly-created resource will be fuzzed using that single resource as a static value, while the create-once resource itself will not be.

**Comment by marina-p** [comment]
Hello @JoshuaEN,

One quick pointer before I've had a chance to look at your example project.

1) If by "unique" you mean one specific "magic value" that should always be used, the way to do this is to specify a restler_custom_payload with the exact path to the parameter or property.  What didn't work when you tried adding restler_custom_payload?

2) We don't support equality constraints yet.  If (1) above is just one static value, you could simply include both properties in restler_custom_payload and specify the same value.

**Comment by JoshuaEN** [comment]
Hi Richard,

Thanks for the suggestion. After some testing, using create_once appears to avoid generating HTTP errors, however it also appears to exclude the resource creation and deletion endpoint from the fuzzing. This makes sense, but ideally it would be possible to fuzz endpoints in the future even if they require unique values as parameters.

That said, this is a good work around. Thanks again!

**Comment by JoshuaEN** [comment]
Hello @marina-p,

Thanks for looking into this. Regarding (1), unique in that the parameter (e.g. `id`) needs to be unique across instances of that resource. A primary key in a database table effectively.

Using the `restler_custom_payload` worked as expected (in that it used the custom payload value instead of the normal fuzzing value), but the REST API requires the parameter is unique across all of that resource.

I think what I want is a way to specify the provider of a parameter as a random generator, maybe like how UUID suffix properties are currently represented in `dependencies.json` for PUT producers?

```json
{
          "producer_endpoint": "",
          "producer_method": "",
          "producer_resource_name": "restler_custom_payload_uuid_suffix__testId",
          "consumer_param": "testId"
}
```
(I tried to add a custom annotation in this style, but it didn't appear to work)

**Comment by marina-p** [comment]
After further investigation - 

1. Re: A way to specify which parameter names for a request (or globally) should be unique

This does not work due to a bug, and we will fix it shortly.  This should work by providing the suffix values the same as custom payload is provided, for example:
```json
  "restler_custom_payload_uuid4_suffix": {
      "resourceId": "resourceprefix",
      "/resource/id": "resourceprefix"
    }
```

This will produce the following grammar:

```
    primitives.restler_custom_payload_uuid4_suffix("resourceId"),
    primitives.restler_static_string(" HTTP/1.1\r\n"),
    ...
    primitives.restler_static_string("{"),
    primitives.restler_static_string("""
    "resource":
        {
            "id":"""),
    primitives.restler_custom_payload_uuid4_suffix("/resource/id"),
    primitives.restler_static_string(""",
...
```

RE: And for those unique parameters, which ones within a request should match (have the same unique value)

This is a new feature needed for cases when the parameters aren't named the same, so a global replacement is not possible (such as in the case above, where "resourceId" and "/resource/id" will get different suffixes in the same request).  The equality constraint will most likely be supported via an annotation.  Unfortunately, for now the only workaround is to modify the grammar.json/grammar.py.

**Comment by JoshuaEN** [comment]
Thank you looking into this further and for the detailed response! It is very helpful to know both of these cases are planned to be supported in the future.
