### ISSUE TITLE
Help needed with NameSpaceRuleChecker

### ISSUE THREAD

**Issue by rennhard** [microsoft/restler-fuzzer#98]
Hello,

I have managed to successfully test several of the checkers using an intentionally vulnerable test application I developed, but so far, I have had no luck with this checker.

The scenario is as follows:

- customer1 can POST messages to /customers/customer1/messages
- customer2 can do the same to /customers/customer2/messages

They can GET a message back (that has a specific messageID) using, e.g.:

- customer1 (who has posted message 1) from /customers/customer1/messages/1
- customer2 (who has posted message 2) from /customers/customer2/messages/2

I have implemented a bug that allows customer2 to access messages from customer1, e.g., GET /customers/customer1/messages/1 works. As I understand this checker, this should be detectable.

Compiling and testing works. The OpenAPI config is correct. `restler test` works correctly and the messageID returned by POST is associated with the corresponding GET request. The test application uses JWTs that have been configured correctly and restler uses the tokens correctly. I've also enable the checker using --enable_checkers namespacerule.

The program that returns the two JWTs is as follows (the first one is of customer1, the second of customer2):

```
#!/usr/bin/env python
import sys
sys.stdout.write("{'customer1':{}, 'customer2':{}}\n")
sys.stdout.write("Authorization: Bearer eyJhbGciOiJIUzI1...\n")
sys.stdout.write("Authorization: Bearer eyJhbGciOiJIUzI1....\n")
```

I'm unsure about the metadata that must be returned as the first line. I suppose that they should include the URL-part that identifies the customer-specific areas, but I cannot find any information about this (Authentication.md does only provide little information).

I added logging to the application that prints the JWT used in the requests from restler. They only use the first token, never the second, so it appear this checker is never invoked at all.

Any help would be appreciated, thanks!

**Comment by rifiles** [comment]
Hi Marc,

Thanks a lot for your thorough writeup.  This checker had been moved out of the default fuzzing strategy and thus neglected in testing.  There looks to be a bug rendering this checker inoperable at the moment. I'll get it fixed today. 

Thanks again!
